/** Raw customer/contact rows from Excel/Zoho export. Keys match spreadsheet headers. */
module.exports = [
  {
    'Created Time': '2026-01-12 10:34:29',
    'Last Modified Time': '2026-01-12 10:34:29',
    'Contact ID': '1252231000037973007',
    'Contact Type': 'customer',
    'Customer Sub Type': 'business',
    'Place of Supply': 'TS',
    'Taxable': 'true',
    'Tax Name': '',
    'Tax Percentage': '',
    'Tax Type': '',
    'Exemption Reason': '',
    'Contact Name': 'Dr. SUVIDHA GANDRA',
    'Customer Number': 'CUS-00050',
    'Display Name': 'Dr. SUVIDHA GANDRA',
    'Company Name': '',
    'Salutation': 'Dr.',
    'First Name': 'SUVIDHA',
    'Last Name': 'GANDRA',
    'EmailID': '',
    'Phone': '+91-7702693939',
    'MobilePhone': '',
    'Skype Identity': '',
    'Facebook': '',
    'Twitter': '',
    'Department': '',
    'Designation': '',
    'Price List': '',
    'Payment Terms': '60',
    'Currency Code': 'INR',
    'GST Treatment': 'business_gst',
    'GST Identification Number (GSTIN)': '36CPYPG1900C1Z2',
    'Notes': '',
    'Website': '',
    'Contact Address ID': '1252231000037973007',
    'Billing Attention': '',
    'Billing Address': '',
    'Billing Street2': '',
    'Billing City': '',
    'Billing State': '',
    'Billing Country': '',
    'Billing Code': '',
    'Billing Phone': '',
    'Billing Fax': '',
    'Shipping Attention': '',
    'Shipping Address': '',
    'Shipping Street2': '',
    'Shipping City': '',
    'Shipping State': '',
    'Shipping Country': '',
    'Shipping Code': '',
    'Shipping Phone': '',
    'Shipping Fax': '',
    'Source': 'user',
    'Last Sync Time': '',
    'Status': 'Active',
    'Primary Contact ID': '1252231000037973009',
    'Bank Account Payment': 'false',
    'Credit Limit': '0.000',
    'CF.CONTACT  ID': 'CON1687',
    'CF.CATEGORY': '',
    'CF.SALES PERSON NAME': 'KOMAL BYSANI',
    'CF.SALES MANAGER': 'SHIVAM PATHAK',
  },
  {
    'Created Time': '2026-01-23 11:05:42',
    'Last Modified Time': '2026-01-23 15:46:19',
    'Contact ID': '1252231000038281097',
    'Contact Type': 'customer',
    'Customer Sub Type': 'business',
    'Place of Supply': 'TS',
    'Taxable': 'true',
    'Tax Name': '',
    'Tax Percentage': '',
    'Tax Type': '',
    'Exemption Reason': '',
    'Contact Name': 'SCULPT PLASTIC SURGERY HYDERABAD LLP',
    'Customer Number': 'CUS-00051',
    'Display Name': 'SCULPT PLASTIC SURGERY HYDERABAD LLP',
    'Company Name': 'SCULPT PLASTIC SURGERY HYDERABAD LLP',
    'Salutation': 'Mr.',
    'First Name': 'Shiva',
    'Last Name': '',
    'EmailID': '',
    'Phone': '+91-9700222661',
    'MobilePhone': '',
    'Skype Identity': '',
    'Facebook': '',
    'Twitter': '',
    'Department': '',
    'Designation': '',
    'Price List': '',
    'Payment Terms': '0',
    'Currency Code': 'INR',
    'GST Treatment': 'business_gst',
    'GST Identification Number (GSTIN)': '36AFDFS7869B1ZP',
    'Notes': '',
    'Website': '',
    'Contact Address ID': '1252231000038281097',
    'Billing Attention': 'SCULPT PLASTIC SURGERY HYDERABAD LLP',
    'Billing Address': '7-1-69/1/25, Flat NO.404, fourth floor, Shobhanadri Apartment, Dharam Karan Road, Ameerpet',
    'Billing Street2': '',
    'Billing City': 'Hyderabad',
    'Billing State': 'Telangana',
    'Billing Country': 'India',
    'Billing Code': '500016',
    'Billing Phone': '9700222661',
    'Billing Fax': '',
    'Shipping Attention': 'SCULPT PLASTIC SURGERY HYDERABAD LLP',
    'Shipping Address': '7-1-69/1/25, Flat NO.404, fourth floor, Shobhanadri Apartment, Dharam Karan Road, Ameerpet',
    'Shipping Street2': '',
    'Shipping City': 'Hyderabad',
    'Shipping State': 'Telangana',
    'Shipping Country': 'India',
    'Shipping Code': '500016',
    'Shipping Phone': '9700222661',
    'Shipping Fax': '',
    'Source': 'user',
    'Last Sync Time': '',
    'Status': 'Active',
    'Primary Contact ID': '1252231000038281099',
    'Bank Account Payment': 'false',
    'Credit Limit': '0.000',
    'CF.CONTACT  ID': 'CON1691',
    'CF.CATEGORY': '',
    'CF.SALES PERSON NAME': 'KOMAL BYSANI',
    'CF.SALES MANAGER': 'SHIVAM PATHAK',
  },
  {
    'Created Time': '2026-02-18 13:21:10',
    'Last Modified Time': '2026-02-18 13:39:15',
    'Contact ID': '1252231000039270602',
    'Contact Type': 'customer',
    'Customer Sub Type': 'business',
    'Place of Supply': 'MH',
    'Taxable': 'true',
    'Tax Name': '',
    'Tax Percentage': '',
    'Tax Type': '',
    'Exemption Reason': '',
    'Contact Name': 'PEP TECHNOLOGIES PRIVATE LIMITED',
    'Customer Number': 'CUS-00052',
    'Display Name': 'PEP TECHNOLOGIES PRIVATE LIMITED',
    'Company Name': 'PEP TECHNOLOGIES PRIVATE LIMITED',
    'Salutation': 'Ms.',
    'First Name': 'Deepali',
    'Last Name': 'Gehani',
    'EmailID': 'deepali.gehani@mcaffeine.com',
    'Phone': '',
    'MobilePhone': '+91-7709327057',
    'Skype Identity': '',
    'Facebook': '',
    'Twitter': '',
    'Department': '',
    'Designation': '',
    'Price List': '',
    'Payment Terms': '0',
    'Currency Code': 'INR',
    'GST Treatment': 'business_gst',
    'GST Identification Number (GSTIN)': '27AAICP2804J1ZC',
    'Notes': '',
    'Website': '',
    'Contact Address ID': '1252231000039270602',
    'Billing Attention': '',
    'Billing Address': '',
    'Billing Street2': '',
    'Billing City': '',
    'Billing State': '',
    'Billing Country': '',
    'Billing Code': '',
    'Billing Phone': '',
    'Billing Fax': '',
    'Shipping Attention': '',
    'Shipping Address': '',
    'Shipping Street2': '',
    'Shipping City': '',
    'Shipping State': '',
    'Shipping Country': '',
    'Shipping Code': '',
    'Shipping Phone': '',
    'Shipping Fax': '',
    'Source': 'user',
    'Last Sync Time': '',
    'Status': 'Active',
    'Primary Contact ID': '1252231000039270604',
    'Bank Account Payment': 'false',
    'Credit Limit': '0.000',
    'CF.CONTACT  ID': 'CON1700',
    'CF.CATEGORY': '',
    'CF.SALES PERSON NAME': 'MADHUPARNA',
    'CF.SALES MANAGER': 'SHIVAM PATHAK',
  },
  {
    'Created Time': '2026-02-21 13:45:00',
    'Last Modified Time': '2026-02-21 13:45:00',
    'Contact ID': '1252231000039427008',
    'Contact Type': 'customer',
    'Customer Sub Type': 'business',
    'Place of Supply': 'TS',
    'Taxable': 'true',
    'Tax Name': '',
    'Tax Percentage': '',
    'Tax Type': '',
    'Exemption Reason': '',
    'Contact Name': 'LOOKS HAIR STUDIO',
    'Customer Number': 'CUS-00053',
    'Display Name': 'LOOKS HAIR STUDIO',
    'Company Name': 'LOOKS HAIR STUDIO',
    'Salutation': 'Mr.',
    'First Name': 'AELUGUPALLI',
    'Last Name': 'VENKATESH',
    'EmailID': '',
    'Phone': '+91-9885532229',
    'MobilePhone': '',
    'Skype Identity': '',
    'Facebook': '',
    'Twitter': '',
    'Department': '',
    'Designation': '',
    'Price List': '',
    'Payment Terms': '0',
    'Currency Code': 'INR',
    'GST Treatment': 'business_gst',
    'GST Identification Number (GSTIN)': '36AAHFL4905C1ZL',
    'Notes': '',
    'Website': '',
    'Contact Address ID': '1252231000039427008',
    'Billing Attention': '',
    'Billing Address': '',
    'Billing Street2': '',
    'Billing City': '',
    'Billing State': '',
    'Billing Country': '',
    'Billing Code': '',
    'Billing Phone': '',
    'Billing Fax': '',
    'Shipping Attention': '',
    'Shipping Address': '',
    'Shipping Street2': '',
    'Shipping City': '',
    'Shipping State': '',
    'Shipping Country': '',
    'Shipping Code': '',
    'Shipping Phone': '',
    'Shipping Fax': '',
    'Source': 'user',
    'Last Sync Time': '',
    'Status': 'Active',
    'Primary Contact ID': '1252231000039427010',
    'Bank Account Payment': 'false',
    'Credit Limit': '0.000',
    'CF.CONTACT  ID': 'CON1703',
    'CF.CATEGORY': '',
    'CF.SALES PERSON NAME': 'KOMAL BYSANI',
    'CF.SALES MANAGER': 'SHIVAM PATHAK',
  },
];
