/** Raw item rows from Excel/Zoho export. Keys match spreadsheet headers. */
module.exports = [
  {
    'Item ID': '1252231000039481630',
    'Created Time': '2026-02-25 15:01:12',
    'Last Modified Time': '2026-02-25 15:56:13',
    'Item Name': 'SKINQ DETAN POST FACIAL_KC CARE 5ML(IND)',
    'Sales Description': '',
    'Selling Price': 'INR 0.00',
    'Sales Account': 'Sales',
    'Is Returnable Item': 'false',
    'Brand': '',
    'Manufacturer': '',
    'Package Weight': '0',
    'Package Length': '0',
    'Package Width': '0',
    'Package Height': '0',
    'Dimension Unit': 'cm',
    'Weight Unit': 'kg',
    'Is Receivable Service': '',
    'Taxable': 'true',
    'Exemption Reason': '',
    'Taxability Type': '',
    'Product Type': 'goods',
    'Source': '1',
    'Reference ID': '',
    'Last Sync Time': '',
    'Status': 'Active',
    'Unit': 'NOS',
    'Unit Name': 'Numbers',
    'SKU': 'PR0007210',
    'HSN/SAC': '',
    'UPC': '',
    'EAN': '',
    'ISBN': '',
    'Part Number': '',
    'Purchase Price': 'INR 0.00',
    'Purchase Account': 'Cost of Goods Sold',
    'Purchase Description': '',
    'Inventory Account': 'Finished Goods',
    'Inventory Valuation Method': 'fifo',
    'Reorder Level': '',
    'Preferred Vendor': '',
    'Warehouse Name': '',
    'Opening Stock': '',
    'Opening Stock Value': '',
    'Stock On Hand': '0',
    'Is Combo Product': 'true',
    'Enable Bin Tracking': 'false',
    'Item Type': 'Inventory',
    'Sellable': 'true',
    'Purchasable': 'true',
    'Track Inventory': 'true',
    'Category Name': '',
    'Parent Category': '',
    'Intra State Tax Name': 'GST18',
    'Intra State Tax Rate': '18.000000',
    'Intra State Tax Type': 'Group',
    'Inter State Tax Name': 'IGST18',
    'Inter State Tax Rate': '18.000000',
    'Inter State Tax Type': 'Simple',
    'CF.ITEM CATEGORY': 'FG- ONGOING',
    'CF.Material Code': '',
    'CF.Supplier': '',
    'CF.Method Of Preparation': '',
    'CF.PH': '',
    'CF.Viscosity': '',
    'CF.Fragrance': '',
    'CF.Texture': '',
    'CF.Appearance': '',
    'CF.DIS Number': '',
    'CF.Batch Number': '',
    'CF.Expiry Date': '',
    'CF.MFG Date': '',
    'CF.PACKAGING R&D POC': '',
    'CF.QUALITY TEAM POC': '',
    'CF.DESIGN TEAM POC': '',
    'CF.MRP': '0.00',
    'CF.PRICE PER UNIT': '18',
    'CF.MOQ': '1000',
    'CF.LEAD TIME': '0',
    'CF.CLIENT NAME': 'HEALTH Q LIFESCIENCES PRIVATE LIMITED',
    'CF.CONTACT ID': 'CON0103',
    'CF.YIELD PERCENTAGE': '',
    'CF.TERGET DEVELOPMENT PRICE': '',
    'CF.PRICE PER KG': '',
    'CF.ITEM STATUS': '',
    'CF.MKT BRAND NAME': 'SKIN Q',
    'CF.SALES PERSON NAME': 'SUNNY YADAV',
    'CF.OLD SKU': '',
    'CF.PREVIOUS SKU': '',
    'CF.INCI NAME': '',
    'CF.MONOCARTON STATUS': '',
    'CF.MONO CARTON PRICE': '',
    'CF.is_group_item': 'false',
  },
  {
    'Item ID': '1252231000039481711',
    'Created Time': '2026-02-25 15:16:29',
    'Last Modified Time': '2026-02-25 15:56:13',
    'Item Name': 'SKINQ DETAN SUN PROTECTION_KC 5ML(IND)',
    'Sales Description': '',
    'Selling Price': 'INR 0.00',
    'Sales Account': 'Sales',
    'Is Returnable Item': 'false',
    'Brand': '',
    'Manufacturer': '',
    'Package Weight': '0',
    'Package Length': '0',
    'Package Width': '0',
    'Package Height': '0',
    'Dimension Unit': 'cm',
    'Weight Unit': 'kg',
    'Is Receivable Service': '',
    'Taxable': 'true',
    'Exemption Reason': '',
    'Taxability Type': '',
    'Product Type': 'goods',
    'Source': '1',
    'Reference ID': '',
    'Last Sync Time': '',
    'Status': 'Active',
    'Unit': 'NOS',
    'Unit Name': 'Numbers',
    'SKU': 'PR0007211',
    'HSN/SAC': '',
    'UPC': '',
    'EAN': '',
    'ISBN': '',
    'Part Number': '',
    'Purchase Price': 'INR 0.00',
    'Purchase Account': 'Cost of Goods Sold',
    'Purchase Description': '',
    'Inventory Account': 'Finished Goods',
    'Inventory Valuation Method': 'fifo',
    'Reorder Level': '',
    'Preferred Vendor': '',
    'Warehouse Name': '',
    'Opening Stock': '',
    'Opening Stock Value': '',
    'Stock On Hand': '0',
    'Is Combo Product': 'true',
    'Enable Bin Tracking': 'false',
    'Item Type': 'Inventory',
    'Sellable': 'true',
    'Purchasable': 'true',
    'Track Inventory': 'true',
    'Category Name': '',
    'Parent Category': '',
    'Intra State Tax Name': 'GST18',
    'Intra State Tax Rate': '18.000000',
    'Intra State Tax Type': 'Group',
    'Inter State Tax Name': 'IGST18',
    'Inter State Tax Rate': '18.000000',
    'Inter State Tax Type': 'Simple',
    'CF.ITEM CATEGORY': 'FG- ONGOING',
    'CF.Material Code': '',
    'CF.Supplier': '',
    'CF.Method Of Preparation': '',
    'CF.PH': '6.400000',
    'CF.Viscosity': '14000',
    'CF.Fragrance': 'YES',
    'CF.Texture': 'GEL',
    'CF.Appearance': 'WHITE',
    'CF.DIS Number': '',
    'CF.Batch Number': '',
    'CF.Expiry Date': '',
    'CF.MFG Date': '',
    'CF.PACKAGING R&D POC': 'SAIF',
    'CF.QUALITY TEAM POC': 'VANI',
    'CF.DESIGN TEAM POC': 'SRINIVAS',
    'CF.MRP': '0.00',
    'CF.PRICE PER UNIT': '10',
    'CF.MOQ': '3000',
    'CF.LEAD TIME': '0',
    'CF.CLIENT NAME': 'HEALTH Q LIFESCIENCES PRIVATE LIMITED',
    'CF.CONTACT ID': 'CON0103',
    'CF.YIELD PERCENTAGE': '',
    'CF.TERGET DEVELOPMENT PRICE': '',
    'CF.PRICE PER KG': '',
    'CF.ITEM STATUS': '',
    'CF.MKT BRAND NAME': 'SKIN Q',
    'CF.SALES PERSON NAME': 'SUNNY YADAV',
    'CF.OLD SKU': '',
    'CF.PREVIOUS SKU': '',
    'CF.INCI NAME': '',
    'CF.MONOCARTON STATUS': '',
    'CF.MONO CARTON PRICE': '',
    'CF.is_group_item': 'false',
  },
  {
    'Item ID': '1252231000039481767',
    'Created Time': '2026-02-25 15:16:53',
    'Last Modified Time': '2026-02-25 15:59:39',
    'Item Name': 'SKINQ HYDRATE SUN PROTECTION_KC 5ML',
    'Sales Description': '',
    'Selling Price': 'INR 0.00',
    'Sales Account': 'Sales',
    'Is Returnable Item': 'false',
    'Brand': '',
    'Manufacturer': '',
    'Package Weight': '0',
    'Package Length': '0',
    'Package Width': '0',
    'Package Height': '0',
    'Dimension Unit': 'cm',
    'Weight Unit': 'kg',
    'Is Receivable Service': '',
    'Taxable': 'true',
    'Exemption Reason': '',
    'Taxability Type': '',
    'Product Type': 'goods',
    'Source': '1',
    'Reference ID': '',
    'Last Sync Time': '',
    'Status': 'Active',
    'Unit': 'NOS',
    'Unit Name': 'Numbers',
    'SKU': 'PR0007213',
    'HSN/SAC': '',
    'UPC': '',
    'EAN': '',
    'ISBN': '',
    'Part Number': '',
    'Purchase Price': 'INR 0.00',
    'Purchase Account': 'Cost of Goods Sold',
    'Purchase Description': '',
    'Inventory Account': 'Finished Goods',
    'Inventory Valuation Method': 'fifo',
    'Reorder Level': '',
    'Preferred Vendor': '',
    'Warehouse Name': '',
    'Opening Stock': '',
    'Opening Stock Value': '',
    'Stock On Hand': '0',
    'Is Combo Product': 'true',
    'Enable Bin Tracking': 'false',
    'Item Type': 'Inventory',
    'Sellable': 'true',
    'Purchasable': 'true',
    'Track Inventory': 'true',
    'Category Name': '',
    'Parent Category': '',
    'Intra State Tax Name': 'GST18',
    'Intra State Tax Rate': '18.000000',
    'Intra State Tax Type': 'Group',
    'Inter State Tax Name': 'IGST18',
    'Inter State Tax Rate': '18.000000',
    'Inter State Tax Type': 'Simple',
    'CF.ITEM CATEGORY': 'FG- ONGOING',
    'CF.Material Code': '',
    'CF.Supplier': '',
    'CF.Method Of Preparation': '',
    'CF.PH': '6.400000',
    'CF.Viscosity': '14000',
    'CF.Fragrance': 'YES',
    'CF.Texture': 'GEL',
    'CF.Appearance': 'WHITE',
    'CF.DIS Number': '',
    'CF.Batch Number': '',
    'CF.Expiry Date': '',
    'CF.MFG Date': '',
    'CF.PACKAGING R&D POC': 'SAIF',
    'CF.QUALITY TEAM POC': 'VANI',
    'CF.DESIGN TEAM POC': 'SRINIVAS',
    'CF.MRP': '0.00',
    'CF.PRICE PER UNIT': '10',
    'CF.MOQ': '3000',
    'CF.LEAD TIME': '0',
    'CF.CLIENT NAME': 'HEALTH Q LIFESCIENCES PRIVATE LIMITED',
    'CF.CONTACT ID': 'CON0103',
    'CF.YIELD PERCENTAGE': '',
    'CF.TERGET DEVELOPMENT PRICE': '',
    'CF.PRICE PER KG': '',
    'CF.ITEM STATUS': '',
    'CF.MKT BRAND NAME': 'SKIN Q',
    'CF.SALES PERSON NAME': 'SUNNY YADAV',
    'CF.OLD SKU': '',
    'CF.PREVIOUS SKU': '',
    'CF.INCI NAME': '',
    'CF.MONOCARTON STATUS': '',
    'CF.MONO CARTON PRICE': '',
    'CF.is_group_item': 'false',
  },
  {
    'Item ID': '1252231000039481823',
    'Created Time': '2026-02-25 15:17:21',
    'Last Modified Time': '2026-02-25 15:59:39',
    'Item Name': 'SKINQ HYDRATE POST FACIAL CARE_KC 5ML',
    'Sales Description': '',
    'Selling Price': 'INR 0.00',
    'Sales Account': 'Sales',
    'Is Returnable Item': 'false',
    'Brand': '',
    'Manufacturer': '',
    'Package Weight': '0',
    'Package Length': '0',
    'Package Width': '0',
    'Package Height': '0',
    'Dimension Unit': 'cm',
    'Weight Unit': 'kg',
    'Is Receivable Service': '',
    'Taxable': 'true',
    'Exemption Reason': '',
    'Taxability Type': '',
    'Product Type': 'goods',
    'Source': '1',
    'Reference ID': '',
    'Last Sync Time': '',
    'Status': 'Active',
    'Unit': 'NOS',
    'Unit Name': 'Numbers',
    'SKU': 'PR0007212',
    'HSN/SAC': '',
    'UPC': '',
    'EAN': '',
    'ISBN': '',
    'Part Number': '',
    'Purchase Price': 'INR 0.00',
    'Purchase Account': 'Cost of Goods Sold',
    'Purchase Description': '',
    'Inventory Account': 'Finished Goods',
    'Inventory Valuation Method': 'fifo',
    'Reorder Level': '',
    'Preferred Vendor': '',
    'Warehouse Name': '',
    'Opening Stock': '',
    'Opening Stock Value': '',
    'Stock On Hand': '0',
    'Is Combo Product': 'true',
    'Enable Bin Tracking': 'false',
    'Item Type': 'Inventory',
    'Sellable': 'true',
    'Purchasable': 'true',
    'Track Inventory': 'true',
    'Category Name': '',
    'Parent Category': '',
    'Intra State Tax Name': 'GST18',
    'Intra State Tax Rate': '18.000000',
    'Intra State Tax Type': 'Group',
    'Inter State Tax Name': 'IGST18',
    'Inter State Tax Rate': '18.000000',
    'Inter State Tax Type': 'Simple',
    'CF.ITEM CATEGORY': 'FG- ONGOING',
    'CF.Material Code': '',
    'CF.Supplier': '',
    'CF.Method Of Preparation': '',
    'CF.PH': '',
    'CF.Viscosity': '',
    'CF.Fragrance': '',
    'CF.Texture': '',
    'CF.Appearance': '',
    'CF.DIS Number': '',
    'CF.Batch Number': '',
    'CF.Expiry Date': '',
    'CF.MFG Date': '',
    'CF.PACKAGING R&D POC': '',
    'CF.QUALITY TEAM POC': '',
    'CF.DESIGN TEAM POC': '',
    'CF.MRP': '0.00',
    'CF.PRICE PER UNIT': '18',
    'CF.MOQ': '1000',
    'CF.LEAD TIME': '0',
    'CF.CLIENT NAME': 'HEALTH Q LIFESCIENCES PRIVATE LIMITED',
    'CF.CONTACT ID': 'CON0103',
    'CF.YIELD PERCENTAGE': '',
    'CF.TERGET DEVELOPMENT PRICE': '',
    'CF.PRICE PER KG': '',
    'CF.ITEM STATUS': '',
    'CF.MKT BRAND NAME': 'SKIN Q',
    'CF.SALES PERSON NAME': 'SUNNY YADAV',
    'CF.OLD SKU': '',
    'CF.PREVIOUS SKU': '',
    'CF.INCI NAME': '',
    'CF.MONOCARTON STATUS': '',
    'CF.MONO CARTON PRICE': '',
    'CF.is_group_item': 'false',
  },
  {
    'Item ID': '1252231000039483208',
    'Created Time': '2026-02-25 15:17:26',
    'Last Modified Time': '2026-02-26 10:03:22',
    'Item Name': 'SKINKRAFT ADVANCE 98% SNAIL NUCIN HYDRATING SERUM 100ML LABEL',
    'Sales Description': '',
    'Selling Price': 'INR 0.00',
    'Sales Account': 'Sales',
    'Is Returnable Item': 'false',
    'Brand': '',
    'Manufacturer': '',
    'Package Weight': '0',
    'Package Length': '0',
    'Package Width': '0',
    'Package Height': '0',
    'Dimension Unit': 'cm',
    'Weight Unit': 'kg',
    'Is Receivable Service': '',
    'Taxable': 'true',
    'Exemption Reason': '',
    'Taxability Type': '',
    'Product Type': 'goods',
    'Source': '1',
    'Reference ID': '',
    'Last Sync Time': '',
    'Status': 'Active',
    'Unit': 'NOS',
    'Unit Name': 'Numbers',
    'SKU': '5L01648',
    'HSN/SAC': '',
    'UPC': '',
    'EAN': '',
    'ISBN': '',
    'Part Number': '',
    'Purchase Price': 'INR 0.00',
    'Purchase Account': 'Cost of Goods Sold',
    'Purchase Description': '',
    'Inventory Account': 'Inventory Asset',
    'Inventory Valuation Method': 'fifo',
    'Reorder Level': '',
    'Preferred Vendor': '',
    'Warehouse Name': '',
    'Opening Stock': '',
    'Opening Stock Value': '',
    'Stock On Hand': '3150',
    'Is Combo Product': 'false',
    'Enable Bin Tracking': 'false',
    'Item Type': 'Inventory',
    'Sellable': 'true',
    'Purchasable': 'true',
    'Track Inventory': 'true',
    'Category Name': '',
    'Parent Category': '',
    'Intra State Tax Name': 'GST18',
    'Intra State Tax Rate': '18.000000',
    'Intra State Tax Type': 'Group',
    'Inter State Tax Name': 'IGST18',
    'Inter State Tax Rate': '18.000000',
    'Inter State Tax Type': 'Simple',
    'CF.ITEM CATEGORY': 'SPM - LABEL',
    'CF.Material Code': '',
    'CF.Supplier': '',
    'CF.Method Of Preparation': '',
    'CF.PH': '',
    'CF.Viscosity': '',
    'CF.Fragrance': '',
    'CF.Texture': '',
    'CF.Appearance': '',
    'CF.DIS Number': '',
    'CF.Batch Number': '',
    'CF.Expiry Date': '',
    'CF.MFG Date': '',
    'CF.PACKAGING R&D POC': '',
    'CF.QUALITY TEAM POC': '',
    'CF.DESIGN TEAM POC': '',
    'CF.MRP': '',
    'CF.PRICE PER UNIT': '',
    'CF.MOQ': '',
    'CF.LEAD TIME': '0',
    'CF.CLIENT NAME': '',
    'CF.CONTACT ID': '',
    'CF.YIELD PERCENTAGE': '',
    'CF.TERGET DEVELOPMENT PRICE': '',
    'CF.PRICE PER KG': '',
    'CF.ITEM STATUS': '',
    'CF.MKT BRAND NAME': '',
    'CF.SALES PERSON NAME': '',
    'CF.OLD SKU': '',
    'CF.PREVIOUS SKU': '',
    'CF.INCI NAME': '',
    'CF.MONOCARTON STATUS': '',
    'CF.MONO CARTON PRICE': '',
    'CF.is_group_item': 'false',
  },
  {
    'Item ID': '1252231000039500277',
    'Created Time': '2026-02-26 10:23:06',
    'Last Modified Time': '2026-02-26 10:23:06',
    'Item Name': 'SKINQ DETAN MASK POWDER 10 GM PRINTED SACHET ( YELLOW )',
    'Sales Description': '',
    'Selling Price': 'INR 0.00',
    'Sales Account': 'Sales',
    'Is Returnable Item': 'false',
    'Brand': '',
    'Manufacturer': '',
    'Package Weight': '0',
    'Package Length': '0',
    'Package Width': '0',
    'Package Height': '0',
    'Dimension Unit': 'cm',
    'Weight Unit': 'kg',
    'Is Receivable Service': '',
    'Taxable': 'true',
    'Exemption Reason': '',
    'Taxability Type': '',
    'Product Type': 'goods',
    'Source': '1',
    'Reference ID': '',
    'Last Sync Time': '',
    'Status': 'Active',
    'Unit': 'NOS',
    'Unit Name': 'Numbers',
    'SKU': '4001167',
    'HSN/SAC': '',
    'UPC': '',
    'EAN': '',
    'ISBN': '',
    'Part Number': '',
    'Purchase Price': 'INR 0.00',
    'Purchase Account': 'Cost of Goods Sold',
    'Purchase Description': '',
    'Inventory Account': 'Inventory Asset',
    'Inventory Valuation Method': 'fifo',
    'Reorder Level': '',
    'Preferred Vendor': '',
    'Warehouse Name': '',
    'Opening Stock': '',
    'Opening Stock Value': '',
    'Stock On Hand': '0',
    'Is Combo Product': 'false',
    'Enable Bin Tracking': 'false',
    'Item Type': 'Inventory',
    'Sellable': 'true',
    'Purchasable': 'true',
    'Track Inventory': 'true',
    'Category Name': '',
    'Parent Category': '',
    'Intra State Tax Name': 'GST18',
    'Intra State Tax Rate': '18.000000',
    'Intra State Tax Type': 'Group',
    'Inter State Tax Name': 'IGST18',
    'Inter State Tax Rate': '18.000000',
    'Inter State Tax Type': 'Simple',
    'CF.ITEM CATEGORY': 'Packaging Material',
    'CF.Material Code': '',
    'CF.Supplier': '',
    'CF.Method Of Preparation': '',
    'CF.PH': '',
    'CF.Viscosity': '',
    'CF.Fragrance': '',
    'CF.Texture': '',
    'CF.Appearance': '',
    'CF.DIS Number': '',
    'CF.Batch Number': '',
    'CF.Expiry Date': '',
    'CF.MFG Date': '',
    'CF.PACKAGING R&D POC': '',
    'CF.QUALITY TEAM POC': '',
    'CF.DESIGN TEAM POC': '',
    'CF.MRP': '',
    'CF.PRICE PER UNIT': '',
    'CF.MOQ': '',
    'CF.LEAD TIME': '0',
    'CF.CLIENT NAME': '',
    'CF.CONTACT ID': '',
    'CF.YIELD PERCENTAGE': '',
    'CF.TERGET DEVELOPMENT PRICE': '',
    'CF.PRICE PER KG': '',
    'CF.ITEM STATUS': '',
    'CF.MKT BRAND NAME': '',
    'CF.SALES PERSON NAME': '',
    'CF.OLD SKU': '',
    'CF.PREVIOUS SKU': '',
    'CF.INCI NAME': '',
    'CF.MONOCARTON STATUS': '',
    'CF.MONO CARTON PRICE': '',
    'CF.is_group_item': 'false',
  },
  {
    'Item ID': '1252231000039513017',
    'Created Time': '2026-02-26 14:48:01',
    'Last Modified Time': '2026-02-26 15:21:59',
    'Item Name': 'YplayZ SLIDE & GLIDE  SUMMER VACATION 40ML',
    'Sales Description': '',
    'Selling Price': 'INR 0.00',
    'Sales Account': 'Sales',
    'Is Returnable Item': 'false',
    'Brand': '',
    'Manufacturer': '',
    'Package Weight': '0',
    'Package Length': '0',
    'Package Width': '0',
    'Package Height': '0',
    'Dimension Unit': 'cm',
    'Weight Unit': 'kg',
    'Is Receivable Service': '',
    'Taxable': 'true',
    'Exemption Reason': '',
    'Taxability Type': '',
    'Product Type': 'goods',
    'Source': '1',
    'Reference ID': '',
    'Last Sync Time': '',
    'Status': 'Active',
    'Unit': 'NOS',
    'Unit Name': 'Numbers',
    'SKU': 'PR0006342',
    'HSN/SAC': '',
    'UPC': '',
    'EAN': '',
    'ISBN': '',
    'Part Number': '',
    'Purchase Price': 'INR 0.00',
    'Purchase Account': 'Cost of Goods Sold',
    'Purchase Description': '',
    'Inventory Account': 'Finished Goods',
    'Inventory Valuation Method': 'fifo',
    'Reorder Level': '',
    'Preferred Vendor': '',
    'Warehouse Name': '',
    'Opening Stock': '',
    'Opening Stock Value': '',
    'Stock On Hand': '0',
    'Is Combo Product': 'true',
    'Enable Bin Tracking': 'false',
    'Item Type': 'Inventory',
    'Sellable': 'true',
    'Purchasable': 'true',
    'Track Inventory': 'true',
    'Category Name': '',
    'Parent Category': '',
    'Intra State Tax Name': 'GST18',
    'Intra State Tax Rate': '18.000000',
    'Intra State Tax Type': 'Group',
    'Inter State Tax Name': 'IGST18',
    'Inter State Tax Rate': '18.000000',
    'Inter State Tax Type': 'Simple',
    'CF.ITEM CATEGORY': '',
    'CF.Material Code': '',
    'CF.Supplier': '',
    'CF.Method Of Preparation': '',
    'CF.PH': '',
    'CF.Viscosity': '',
    'CF.Fragrance': '',
    'CF.Texture': '',
    'CF.Appearance': '',
    'CF.DIS Number': '',
    'CF.Batch Number': '',
    'CF.Expiry Date': '',
    'CF.MFG Date': '',
    'CF.PACKAGING R&D POC': '',
    'CF.QUALITY TEAM POC': '',
    'CF.DESIGN TEAM POC': '',
    'CF.MRP': '',
    'CF.PRICE PER UNIT': '',
    'CF.MOQ': '',
    'CF.LEAD TIME': '0',
    'CF.CLIENT NAME': '',
    'CF.CONTACT ID': '',
    'CF.YIELD PERCENTAGE': '',
    'CF.TERGET DEVELOPMENT PRICE': '',
    'CF.PRICE PER KG': '',
    'CF.ITEM STATUS': '',
    'CF.MKT BRAND NAME': '',
    'CF.SALES PERSON NAME': '',
    'CF.OLD SKU': '',
    'CF.PREVIOUS SKU': '',
    'CF.INCI NAME': '',
    'CF.MONOCARTON STATUS': '',
    'CF.MONO CARTON PRICE': '',
    'CF.is_group_item': 'false',
  },
  {
    'Item ID': '1252231000039513142',
    'Created Time': '2026-02-26 15:23:25',
    'Last Modified Time': '2026-02-26 15:23:25',
    'Item Name': 'YplayZ SLIDE & GLIDE  TALK TO THE PALM 40ML',
    'Sales Description': '',
    'Selling Price': 'INR 0.00',
    'Sales Account': 'Sales',
    'Is Returnable Item': 'false',
    'Brand': '',
    'Manufacturer': '',
    'Package Weight': '0',
    'Package Length': '0',
    'Package Width': '0',
    'Package Height': '0',
    'Dimension Unit': 'cm',
    'Weight Unit': 'kg',
    'Is Receivable Service': '',
    'Taxable': 'true',
    'Exemption Reason': '',
    'Taxability Type': '',
    'Product Type': 'goods',
    'Source': '1',
    'Reference ID': '',
    'Last Sync Time': '',
    'Status': 'Active',
    'Unit': 'NOS',
    'Unit Name': 'Numbers',
    'SKU': 'PR0006702',
    'HSN/SAC': '',
    'UPC': '',
    'EAN': '',
    'ISBN': '',
    'Part Number': '',
    'Purchase Price': 'INR 0.00',
    'Purchase Account': 'Cost of Goods Sold',
    'Purchase Description': '',
    'Inventory Account': 'Finished Goods',
    'Inventory Valuation Method': 'fifo',
    'Reorder Level': '',
    'Preferred Vendor': '',
    'Warehouse Name': '',
    'Opening Stock': '',
    'Opening Stock Value': '',
    'Stock On Hand': '0',
    'Is Combo Product': 'true',
    'Enable Bin Tracking': 'false',
    'Item Type': 'Inventory',
    'Sellable': 'true',
    'Purchasable': 'true',
    'Track Inventory': 'true',
    'Category Name': '',
    'Parent Category': '',
    'Intra State Tax Name': 'GST18',
    'Intra State Tax Rate': '18.000000',
    'Intra State Tax Type': 'Group',
    'Inter State Tax Name': 'IGST18',
    'Inter State Tax Rate': '18.000000',
    'Inter State Tax Type': 'Simple',
    'CF.ITEM CATEGORY': '',
    'CF.Material Code': '',
    'CF.Supplier': '',
    'CF.Method Of Preparation': '',
    'CF.PH': '',
    'CF.Viscosity': '',
    'CF.Fragrance': '',
    'CF.Texture': '',
    'CF.Appearance': '',
    'CF.DIS Number': '',
    'CF.Batch Number': '',
    'CF.Expiry Date': '',
    'CF.MFG Date': '',
    'CF.PACKAGING R&D POC': '',
    'CF.QUALITY TEAM POC': '',
    'CF.DESIGN TEAM POC': '',
    'CF.MRP': '',
    'CF.PRICE PER UNIT': '',
    'CF.MOQ': '',
    'CF.LEAD TIME': '0',
    'CF.CLIENT NAME': '',
    'CF.CONTACT ID': '',
    'CF.YIELD PERCENTAGE': '',
    'CF.TERGET DEVELOPMENT PRICE': '',
    'CF.PRICE PER KG': '',
    'CF.ITEM STATUS': '',
    'CF.MKT BRAND NAME': '',
    'CF.SALES PERSON NAME': '',
    'CF.OLD SKU': '',
    'CF.PREVIOUS SKU': '',
    'CF.INCI NAME': '',
    'CF.MONOCARTON STATUS': '',
    'CF.MONO CARTON PRICE': '',
    'CF.is_group_item': 'false',
  },
  {
    'Item ID': '1252231000039513207',
    'Created Time': '2026-02-26 15:24:06',
    'Last Modified Time': '2026-02-26 15:24:06',
    'Item Name': "YplayZ SLIDE & GLIDE  YOU'RE THE ZEST 40ML",
    'Sales Description': '',
    'Selling Price': 'INR 0.00',
    'Sales Account': 'Sales',
    'Is Returnable Item': 'false',
    'Brand': '',
    'Manufacturer': '',
    'Package Weight': '0',
    'Package Length': '0',
    'Package Width': '0',
    'Package Height': '0',
    'Dimension Unit': 'cm',
    'Weight Unit': 'kg',
    'Is Receivable Service': '',
    'Taxable': 'true',
    'Exemption Reason': '',
    'Taxability Type': '',
    'Product Type': 'goods',
    'Source': '1',
    'Reference ID': '',
    'Last Sync Time': '',
    'Status': 'Active',
    'Unit': 'NOS',
    'Unit Name': 'Numbers',
    'SKU': 'PR0006701',
    'HSN/SAC': '',
    'UPC': '',
    'EAN': '',
    'ISBN': '',
    'Part Number': '',
    'Purchase Price': 'INR 0.00',
    'Purchase Account': 'Cost of Goods Sold',
    'Purchase Description': '',
    'Inventory Account': 'Finished Goods',
    'Inventory Valuation Method': 'fifo',
    'Reorder Level': '',
    'Preferred Vendor': '',
    'Warehouse Name': '',
    'Opening Stock': '',
    'Opening Stock Value': '',
    'Stock On Hand': '0',
    'Is Combo Product': 'true',
    'Enable Bin Tracking': 'false',
    'Item Type': 'Inventory',
    'Sellable': 'true',
    'Purchasable': 'true',
    'Track Inventory': 'true',
    'Category Name': '',
    'Parent Category': '',
    'Intra State Tax Name': 'GST18',
    'Intra State Tax Rate': '18.000000',
    'Intra State Tax Type': 'Group',
    'Inter State Tax Name': 'IGST18',
    'Inter State Tax Rate': '18.000000',
    'Inter State Tax Type': 'Simple',
    'CF.ITEM CATEGORY': '',
    'CF.Material Code': '',
    'CF.Supplier': '',
    'CF.Method Of Preparation': '',
    'CF.PH': '',
    'CF.Viscosity': '',
    'CF.Fragrance': '',
    'CF.Texture': '',
    'CF.Appearance': '',
    'CF.DIS Number': '',
    'CF.Batch Number': '',
    'CF.Expiry Date': '',
    'CF.MFG Date': '',
    'CF.PACKAGING R&D POC': '',
    'CF.QUALITY TEAM POC': '',
    'CF.DESIGN TEAM POC': '',
    'CF.MRP': '',
    'CF.PRICE PER UNIT': '',
    'CF.MOQ': '',
    'CF.LEAD TIME': '0',
    'CF.CLIENT NAME': '',
    'CF.CONTACT ID': '',
    'CF.YIELD PERCENTAGE': '',
    'CF.TERGET DEVELOPMENT PRICE': '',
    'CF.PRICE PER KG': '',
    'CF.ITEM STATUS': '',
    'CF.MKT BRAND NAME': '',
    'CF.SALES PERSON NAME': '',
    'CF.OLD SKU': '',
    'CF.PREVIOUS SKU': '',
    'CF.INCI NAME': '',
    'CF.MONOCARTON STATUS': '',
    'CF.MONO CARTON PRICE': '',
    'CF.is_group_item': 'false',
  },
  {
    'Item ID': '1252231000039500756',
    'Created Time': '2026-02-26 17:14:44',
    'Last Modified Time': '2026-02-26 17:14:44',
    'Item Name': 'SKINKRAFT BARRIER REVIATLIZING LOTION FOR OILY SKIN LABEL (new)',
    'Sales Description': '',
    'Selling Price': 'INR 0.00',
    'Sales Account': 'Sales',
    'Is Returnable Item': 'false',
    'Brand': '',
    'Manufacturer': '',
    'Package Weight': '0',
    'Package Length': '0',
    'Package Width': '0',
    'Package Height': '0',
    'Dimension Unit': 'cm',
    'Weight Unit': 'kg',
    'Is Receivable Service': '',
    'Taxable': 'true',
    'Exemption Reason': '',
    'Taxability Type': '',
    'Product Type': 'goods',
    'Source': '1',
    'Reference ID': '',
    'Last Sync Time': '',
    'Status': 'Active',
    'Unit': 'NOS',
    'Unit Name': 'Numbers',
    'SKU': '5L01649',
    'HSN/SAC': '',
    'UPC': '',
    'EAN': '',
    'ISBN': '',
    'Part Number': '',
    'Purchase Price': 'INR 0.00',
    'Purchase Account': 'Cost of Goods Sold',
    'Purchase Description': '',
    'Inventory Account': 'Inventory Asset',
    'Inventory Valuation Method': 'fifo',
    'Reorder Level': '',
    'Preferred Vendor': '',
    'Warehouse Name': '',
    'Opening Stock': '',
    'Opening Stock Value': '',
    'Stock On Hand': '0',
    'Is Combo Product': 'false',
    'Enable Bin Tracking': 'false',
    'Item Type': 'Inventory',
    'Sellable': 'true',
    'Purchasable': 'true',
    'Track Inventory': 'true',
    'Category Name': '',
    'Parent Category': '',
    'Intra State Tax Name': 'GST18',
    'Intra State Tax Rate': '18.000000',
    'Intra State Tax Type': 'Group',
    'Inter State Tax Name': 'IGST18',
    'Inter State Tax Rate': '18.000000',
    'Inter State Tax Type': 'Simple',
    'CF.ITEM CATEGORY': 'SPM - LABEL',
    'CF.Material Code': '',
    'CF.Supplier': '',
    'CF.Method Of Preparation': '',
    'CF.PH': '',
    'CF.Viscosity': '',
    'CF.Fragrance': '',
    'CF.Texture': '',
    'CF.Appearance': '',
    'CF.DIS Number': '',
    'CF.Batch Number': '',
    'CF.Expiry Date': '',
    'CF.MFG Date': '',
    'CF.PACKAGING R&D POC': '',
    'CF.QUALITY TEAM POC': '',
    'CF.DESIGN TEAM POC': '',
    'CF.MRP': '',
    'CF.PRICE PER UNIT': '',
    'CF.MOQ': '',
    'CF.LEAD TIME': '0',
    'CF.CLIENT NAME': '',
    'CF.CONTACT ID': '',
    'CF.YIELD PERCENTAGE': '',
    'CF.TERGET DEVELOPMENT PRICE': '',
    'CF.PRICE PER KG': '',
    'CF.ITEM STATUS': '',
    'CF.MKT BRAND NAME': '',
    'CF.SALES PERSON NAME': '',
    'CF.OLD SKU': '',
    'CF.PREVIOUS SKU': '',
    'CF.INCI NAME': '',
    'CF.MONOCARTON STATUS': '',
    'CF.MONO CARTON PRICE': '',
    'CF.is_group_item': 'false',
  },
];
