const { DataTypes, Model } = require('sequelize');
const db = require('../../db');

/** Maps Excel/Zoho export row (header names) to DB column names (snake_case). */
function excelRowToItem(row) {
  const map = {
    'Item ID': 'item_id',
    'Created Time': 'created_time',
    'Last Modified Time': 'last_modified_time',
    'Item Name': 'item_name',
    'Sales Description': 'sales_description',
    'Selling Price': 'selling_price',
    'Sales Account': 'sales_account',
    'Is Returnable Item': 'is_returnable_item',
    'Brand': 'brand',
    'Manufacturer': 'manufacturer',
    'Package Weight': 'package_weight',
    'Package Length': 'package_length',
    'Package Width': 'package_width',
    'Package Height': 'package_height',
    'Dimension Unit': 'dimension_unit',
    'Weight Unit': 'weight_unit',
    'Is Receivable Service': 'is_receivable_service',
    'Taxable': 'taxable',
    'Exemption Reason': 'exemption_reason',
    'Taxability Type': 'taxability_type',
    'Product Type': 'product_type',
    'Source': 'source',
    'Reference ID': 'reference_id',
    'Last Sync Time': 'last_sync_time',
    'Status': 'status',
    'Unit': 'unit',
    'Unit Name': 'unit_name',
    'SKU': 'sku',
    'HSN/SAC': 'hsn_sac',
    'UPC': 'upc',
    'EAN': 'ean',
    'ISBN': 'isbn',
    'Part Number': 'part_number',
    'Purchase Price': 'purchase_price',
    'Purchase Account': 'purchase_account',
    'Purchase Description': 'purchase_description',
    'Inventory Account': 'inventory_account',
    'Inventory Valuation Method': 'inventory_valuation_method',
    'Reorder Level': 'reorder_level',
    'Preferred Vendor': 'preferred_vendor',
    'Warehouse Name': 'warehouse_name',
    'Opening Stock': 'opening_stock',
    'Opening Stock Value': 'opening_stock_value',
    'Stock On Hand': 'stock_on_hand',
    'Is Combo Product': 'is_combo_product',
    'Enable Bin Tracking': 'enable_bin_tracking',
    'Item Type': 'item_type',
    'Sellable': 'sellable',
    'Purchasable': 'purchasable',
    'Track Inventory': 'track_inventory',
    'Category Name': 'category_name',
    'Parent Category': 'parent_category',
    'Intra State Tax Name': 'intra_state_tax_name',
    'Intra State Tax Rate': 'intra_state_tax_rate',
    'Intra State Tax Type': 'intra_state_tax_type',
    'Inter State Tax Name': 'inter_state_tax_name',
    'Inter State Tax Rate': 'inter_state_tax_rate',
    'Inter State Tax Type': 'inter_state_tax_type',
    'CF.ITEM CATEGORY': 'cf_item_category',
    'CF.Material Code': 'cf_material_code',
    'CF.Supplier': 'cf_supplier',
    'CF.Method Of Preparation': 'cf_method_of_preparation',
    'CF.PH': 'cf_ph',
    'CF.Viscosity': 'cf_viscosity',
    'CF.Fragrance': 'cf_fragrance',
    'CF.Texture': 'cf_texture',
    'CF.Appearance': 'cf_appearance',
    'CF.DIS Number': 'cf_dis_number',
    'CF.Batch Number': 'cf_batch_number',
    'CF.Expiry Date': 'cf_expiry_date',
    'CF.MFG Date': 'cf_mfg_date',
    'CF.PACKAGING R&D POC': 'cf_packaging_rd_poc',
    'CF.QUALITY TEAM POC': 'cf_quality_team_poc',
    'CF.DESIGN TEAM POC': 'cf_design_team_poc',
    'CF.MRP': 'cf_mrp',
    'CF.PRICE PER UNIT': 'cf_price_per_unit',
    'CF.MOQ': 'cf_moq',
    'CF.LEAD TIME': 'cf_lead_time',
    'CF.CLIENT NAME': 'cf_client_name',
    'CF.CONTACT ID': 'cf_contact_id',
    'CF.YIELD PERCENTAGE': 'cf_yield_percentage',
    'CF.TERGET DEVELOPMENT PRICE': 'cf_terget_development_price',
    'CF.PRICE PER KG': 'cf_price_per_kg',
    'CF.ITEM STATUS': 'cf_item_status',
    'CF.MKT BRAND NAME': 'cf_mkt_brand_name',
    'CF.SALES PERSON NAME': 'cf_sales_person_name',
    'CF.OLD SKU': 'cf_old_sku',
    'CF.PREVIOUS SKU': 'cf_previous_sku',
    'CF.INCI NAME': 'cf_inci_name',
    'CF.MONOCARTON STATUS': 'cf_monocarton_status',
    'CF.MONO CARTON PRICE': 'cf_mono_carton_price',
    'CF.is_group_item': 'cf_is_group_item',
  };
  const out = {};
  for (const [key, value] of Object.entries(row)) {
    const col = map[key];
    if (col) out[col] = value != null ? String(value) : '';
  }
  return out;
}

const stringCol = { type: DataTypes.STRING(500), allowNull: true };
const textCol = { type: DataTypes.TEXT, allowNull: true };

class Item extends Model {}

Item.init(
  {
    item_id: { type: DataTypes.STRING(100), primaryKey: true, allowNull: false },
    created_time: stringCol,
    last_modified_time: stringCol,
    item_name: stringCol,
    sales_description: textCol,
    selling_price: stringCol,
    sales_account: stringCol,
    is_returnable_item: stringCol,
    brand: stringCol,
    manufacturer: stringCol,
    package_weight: stringCol,
    package_length: stringCol,
    package_width: stringCol,
    package_height: stringCol,
    dimension_unit: stringCol,
    weight_unit: stringCol,
    is_receivable_service: stringCol,
    taxable: stringCol,
    exemption_reason: stringCol,
    taxability_type: stringCol,
    product_type: stringCol,
    source: stringCol,
    reference_id: stringCol,
    last_sync_time: stringCol,
    status: stringCol,
    unit: stringCol,
    unit_name: stringCol,
    sku: stringCol,
    hsn_sac: stringCol,
    upc: stringCol,
    ean: stringCol,
    isbn: stringCol,
    part_number: stringCol,
    purchase_price: stringCol,
    purchase_account: stringCol,
    purchase_description: textCol,
    inventory_account: stringCol,
    inventory_valuation_method: stringCol,
    reorder_level: stringCol,
    preferred_vendor: stringCol,
    warehouse_name: stringCol,
    opening_stock: stringCol,
    opening_stock_value: stringCol,
    stock_on_hand: stringCol,
    is_combo_product: stringCol,
    enable_bin_tracking: stringCol,
    item_type: stringCol,
    sellable: stringCol,
    purchasable: stringCol,
    track_inventory: stringCol,
    category_name: stringCol,
    parent_category: stringCol,
    intra_state_tax_name: stringCol,
    intra_state_tax_rate: stringCol,
    intra_state_tax_type: stringCol,
    inter_state_tax_name: stringCol,
    inter_state_tax_rate: stringCol,
    inter_state_tax_type: stringCol,
    cf_item_category: stringCol,
    cf_material_code: stringCol,
    cf_supplier: stringCol,
    cf_method_of_preparation: stringCol,
    cf_ph: stringCol,
    cf_viscosity: stringCol,
    cf_fragrance: stringCol,
    cf_texture: stringCol,
    cf_appearance: stringCol,
    cf_dis_number: stringCol,
    cf_batch_number: stringCol,
    cf_expiry_date: stringCol,
    cf_mfg_date: stringCol,
    cf_packaging_rd_poc: stringCol,
    cf_quality_team_poc: stringCol,
    cf_design_team_poc: stringCol,
    cf_mrp: stringCol,
    cf_price_per_unit: stringCol,
    cf_moq: stringCol,
    cf_lead_time: stringCol,
    cf_client_name: stringCol,
    cf_contact_id: stringCol,
    cf_yield_percentage: stringCol,
    cf_terget_development_price: stringCol,
    cf_price_per_kg: stringCol,
    cf_item_status: stringCol,
    cf_mkt_brand_name: stringCol,
    cf_sales_person_name: stringCol,
    cf_old_sku: stringCol,
    cf_previous_sku: stringCol,
    cf_inci_name: stringCol,
    cf_monocarton_status: stringCol,
    cf_mono_carton_price: stringCol,
    cf_is_group_item: stringCol,
  },
  {
    sequelize: db,
    modelName: 'Item',
    tableName: 'items',
    timestamps: false,
  }
);

module.exports = { Item, excelRowToItem };
