/** Raw contact/vendor rows from Excel/Zoho export. Keys match spreadsheet headers. */
module.exports = [
  {
    'Created Time': '2026-01-07 17:56:16',
    'Last Modified Time': '2026-01-22 17:25:04',
    'Contact ID': '1252231000037883012',
    'Source of Supply': 'MH',
    'Taxable': 'true',
    'Contact Name': 'ELEMENTS BIOTECH',
    'Display Name': 'ELEMENTS BIOTECH',
    'Company Name': 'ELEMENTS BIOTECH',
    'Salutation': '',
    'First Name': '',
    'Last Name': '',
    'EmailID': 'azad@elementsbiotech.com',
    'Phone': '+91-9004730372',
    'MobilePhone': '',
    'Skype Identity': '',
    'Facebook': '',
    'Twitter': '',
    'Department': '',
    'Designation': '',
    'Price List': '',
    'Currency Code': 'INR',
    'GST Treatment': 'business_gst',
    'GST Identification Number (GSTIN)': '27AALFE7652H1Z3',
    'MSME/Udyam No': '',
    'MSME/Udyam Type': '',
    'Notes': '',
    'Website': '',
    'Contact Address ID': '1252231000037883012',
    'Billing Attention': 'ELEMENTS BIOTECH',
    'Billing Address': 'Wholesale Business, Office / Sale Office,4 Floor B-410, Kemp Plaza, Chincholi Bunder Road,Malad West',
    'Billing Street2': 'Mumbai',
    'Billing City': 'Mumbai Suburban',
    'Billing State': 'Maharashtra',
    'Billing Country': 'India',
    'Billing Code': '400064',
    'Billing Phone': '+91-9004730372',
    'Billing Fax': '',
    'Shipping Attention': 'ELEMENTS BIOTECH',
    'Shipping Address': 'Wholesale Business, Office / Sale Office,4 Floor B-410, Kemp Plaza, Chincholi Bunder Road,Malad West',
    'Shipping Street2': 'Mumbai',
    'Shipping City': 'Mumbai Suburban',
    'Shipping State': 'Maharashtra',
    'Shipping Country': 'India',
    'Shipping Code': '400064',
    'Shipping Phone': '+91-9004730372',
    'Shipping Fax': '',
    'Source': '1',
    'Last Sync Time': '',
    'Status': 'Active',
    'Primary Contact ID': '1252231000037883014',
    'Beneficiary Name': '',
    'Vendor Bank Account Number': '',
    'Vendor Bank Name': '',
    'Vendor Bank Code': '',
    'CF.CONTACT  ID': 'CON1684',
    'CF.CATEGORY': '',
    'CF.SALES PERSON NAME': 'SAI',
    'CF.SALES MANAGER': 'SAI',
  },
  {
    'Created Time': '2026-01-10 11:56:09',
    'Last Modified Time': '2026-01-10 11:56:09',
    'Contact ID': '1252231000037876300',
    'Source of Supply': 'TS',
    'Taxable': 'true',
    'Contact Name': 'Dr. Kishore Vattikoti',
    'Display Name': 'Dr. Kishore Vattikoti',
    'Company Name': 'Dr. Kishore Vattikoti',
    'Salutation': '',
    'First Name': '',
    'Last Name': '',
    'EmailID': '',
    'Phone': '',
    'MobilePhone': '',
    'Skype Identity': '',
    'Facebook': '',
    'Twitter': '',
    'Department': '',
    'Designation': '',
    'Price List': '',
    'Currency Code': 'INR',
    'GST Treatment': 'business_none',
    'GST Identification Number (GSTIN)': '',
    'MSME/Udyam No': '',
    'MSME/Udyam Type': '',
    'Notes': '',
    'Website': '',
    'Contact Address ID': '1252231000037876300',
    'Billing Attention': '',
    'Billing Address': '',
    'Billing Street2': '',
    'Billing City': '',
    'Billing State': '',
    'Billing Country': '',
    'Billing Code': '',
    'Billing Phone': '',
    'Billing Fax': '',
    'Shipping Attention': '',
    'Shipping Address': '',
    'Shipping Street2': '',
    'Shipping City': '',
    'Shipping State': '',
    'Shipping Country': '',
    'Shipping Code': '',
    'Shipping Phone': '',
    'Shipping Fax': '',
    'Source': '1',
    'Last Sync Time': '',
    'Status': 'Active',
    'Primary Contact ID': '',
    'Beneficiary Name': '',
    'Vendor Bank Account Number': '',
    'Vendor Bank Name': '',
    'Vendor Bank Code': '',
    'CF.CONTACT  ID': 'CON1685',
    'CF.CATEGORY': 'VENDORS-LEGAL CONSULTANTS',
    'CF.SALES PERSON NAME': 'SAI',
    'CF.SALES MANAGER': 'SAI',
  },
  {
    'Created Time': '2026-01-10 18:12:35',
    'Last Modified Time': '2026-01-10 18:12:35',
    'Contact ID': '1252231000037934003',
    'Source of Supply': 'TS',
    'Taxable': 'true',
    'Contact Name': 'David Electrical Works And Electronics',
    'Display Name': 'David Electrical Works And Electronics',
    'Company Name': 'David Electrical Works And Electronics',
    'Salutation': '',
    'First Name': '',
    'Last Name': '',
    'EmailID': 'poduri.david@gmail.com',
    'Phone': '+91-9912547247',
    'MobilePhone': '',
    'Skype Identity': '',
    'Facebook': '',
    'Twitter': '',
    'Department': '',
    'Designation': '',
    'Price List': '',
    'Currency Code': 'INR',
    'GST Treatment': 'business_none',
    'GST Identification Number (GSTIN)': '',
    'MSME/Udyam No': '',
    'MSME/Udyam Type': '',
    'Notes': '',
    'Website': '',
    'Contact Address ID': '1252231000037934003',
    'Billing Attention': 'David Electrical Works And Electronics',
    'Billing Address': 'Hyderabad, secunderabad,new Bowenpally, Sancharapuri ,',
    'Billing Street2': 'Hyderabad, Telangana, 500011',
    'Billing City': 'Hyderabad',
    'Billing State': 'Telangana',
    'Billing Country': 'India',
    'Billing Code': '500011',
    'Billing Phone': '+91-9912547247',
    'Billing Fax': '',
    'Shipping Attention': 'David Electrical Works And Electronics',
    'Shipping Address': 'Hyderabad, secunderabad,new Bowenpally, Sancharapuri ,',
    'Shipping Street2': 'Hyderabad, Telangana, 500011',
    'Shipping City': 'Hyderabad',
    'Shipping State': 'Telangana',
    'Shipping Country': 'India',
    'Shipping Code': '500011',
    'Shipping Phone': '+91-9912547247',
    'Shipping Fax': '',
    'Source': '1',
    'Last Sync Time': '',
    'Status': 'Active',
    'Primary Contact ID': '1252231000037934005',
    'Beneficiary Name': '',
    'Vendor Bank Account Number': '',
    'Vendor Bank Name': '',
    'Vendor Bank Code': '',
    'CF.CONTACT  ID': 'CON1686',
    'CF.CATEGORY': '',
    'CF.SALES PERSON NAME': 'SAI',
    'CF.SALES MANAGER': 'SAI',
  },
  {
    'Created Time': '2026-01-12 11:58:27',
    'Last Modified Time': '2026-01-12 11:58:27',
    'Contact ID': '1252231000037973467',
    'Source of Supply': 'DL',
    'Taxable': 'true',
    'Contact Name': 'NUPLANET VENTURES INDIA PRIVATE LIMITED',
    'Display Name': 'NUPLANET VENTURES INDIA PRIVATE LIMITED',
    'Company Name': 'NUPLANET VENTURES INDIA PRIVATE LIMITED',
    'Salutation': '',
    'First Name': '',
    'Last Name': '',
    'EmailID': 'shadab.khan@rawble.com',
    'Phone': '+91-93191 54361',
    'MobilePhone': '',
    'Skype Identity': '',
    'Facebook': '',
    'Twitter': '',
    'Department': '',
    'Designation': '',
    'Price List': '',
    'Currency Code': 'INR',
    'GST Treatment': 'business_gst',
    'GST Identification Number (GSTIN)': '07AAFCN9850K1ZX',
    'MSME/Udyam No': '',
    'MSME/Udyam Type': '',
    'Notes': '',
    'Website': '',
    'Contact Address ID': '1252231000037973467',
    'Billing Attention': 'NUPLANET VENTURES INDIA PRIVATE LIMITED',
    'Billing Address': 'Office / Sale Office B-51, , Okhla Industrial Phase 1 Road',
    'Billing Street2': 'New Delhi',
    'Billing City': 'South East Delhi',
    'Billing State': 'Delhi',
    'Billing Country': 'India',
    'Billing Code': '110020',
    'Billing Phone': '+91-93191 54361',
    'Billing Fax': '',
    'Shipping Attention': 'NUPLANET VENTURES INDIA PRIVATE LIMITED',
    'Shipping Address': 'Office / Sale Office B-51, , Okhla Industrial Phase 1 Road',
    'Shipping Street2': 'New Delhi',
    'Shipping City': 'South East Delhi',
    'Shipping State': 'Delhi',
    'Shipping Country': 'India',
    'Shipping Code': '110020',
    'Shipping Phone': '+91-93191 54361',
    'Shipping Fax': '',
    'Source': '1',
    'Last Sync Time': '',
    'Status': 'Active',
    'Primary Contact ID': '1252231000037973469',
    'Beneficiary Name': '',
    'Vendor Bank Account Number': '',
    'Vendor Bank Name': '',
    'Vendor Bank Code': '',
    'CF.CONTACT  ID': 'CON1688',
    'CF.CATEGORY': '',
    'CF.SALES PERSON NAME': 'SAI',
    'CF.SALES MANAGER': 'SAI',
  },
  {
    'Created Time': '2026-01-20 13:44:00',
    'Last Modified Time': '2026-01-20 13:44:00',
    'Contact ID': '1252231000038175227',
    'Source of Supply': 'MH',
    'Taxable': 'true',
    'Contact Name': 'RISHIT ENTERPRISES',
    'Display Name': 'RISHIT ENTERPRISES',
    'Company Name': 'RISHIT ENTERPRISES',
    'Salutation': 'Mr.',
    'First Name': 'RAHUL',
    'Last Name': '',
    'EmailID': 'rahul@inncoslifesciences.com',
    'Phone': '+91-9820212353',
    'MobilePhone': '',
    'Skype Identity': '',
    'Facebook': '',
    'Twitter': '',
    'Department': '',
    'Designation': '',
    'Price List': '',
    'Currency Code': 'INR',
    'GST Treatment': 'business_gst',
    'GST Identification Number (GSTIN)': '27AJQPM0845A1ZB',
    'MSME/Udyam No': '',
    'MSME/Udyam Type': '',
    'Notes': '',
    'Website': '',
    'Contact Address ID': '1252231000038175227',
    'Billing Attention': 'RISHIT ENTERPRISES',
    'Billing Address': 'Shop No. 07, Sahara CHS, Plot No. 17 Sector 40',
    'Billing Street2': 'Navi Mumbai',
    'Billing City': 'Thane',
    'Billing State': 'Maharashtra',
    'Billing Country': 'India',
    'Billing Code': '400706',
    'Billing Phone': '',
    'Billing Fax': '',
    'Shipping Attention': 'RISHIT ENTERPRISES',
    'Shipping Address': 'Shop No. 07, Sahara CHS, Plot No. 17 Sector 40',
    'Shipping Street2': 'Navi Mumbai',
    'Shipping City': 'Thane',
    'Shipping State': 'Maharashtra',
    'Shipping Country': 'India',
    'Shipping Code': '400706',
    'Shipping Phone': '',
    'Shipping Fax': '',
    'Source': '1',
    'Last Sync Time': '',
    'Status': 'Active',
    'Primary Contact ID': '1252231000038175229',
    'Beneficiary Name': 'RISHIT ENTERPRISES',
    'Vendor Bank Account Number': '5172000100138601',
    'Vendor Bank Name': 'KARNATAKA BANK',
    'Vendor Bank Code': 'KARB0000517',
    'CF.CONTACT  ID': 'CON1689',
    'CF.CATEGORY': 'VENDORS - COGS-RAW MATERIAL',
    'CF.SALES PERSON NAME': 'SAI',
    'CF.SALES MANAGER': 'SAI',
  },
  {
    'Created Time': '2026-01-20 15:40:15',
    'Last Modified Time': '2026-01-20 15:40:15',
    'Contact ID': '1252231000038172750',
    'Source of Supply': 'TS',
    'Taxable': 'true',
    'Contact Name': 'SRI LAKSHMI ENTERPRISES',
    'Display Name': 'SRI LAKSHMI ENTERPRISES',
    'Company Name': 'SRI LAKSHMI ENTERPRISES',
    'Salutation': '',
    'First Name': '',
    'Last Name': '',
    'EmailID': '',
    'Phone': '+91-8096885694',
    'MobilePhone': '+91-9346640996',
    'Skype Identity': '',
    'Facebook': '',
    'Twitter': '',
    'Department': '',
    'Designation': '',
    'Price List': '',
    'Currency Code': 'INR',
    'GST Treatment': 'business_gst',
    'GST Identification Number (GSTIN)': '36AVTPK8749E1ZW',
    'MSME/Udyam No': '',
    'MSME/Udyam Type': '',
    'Notes': '',
    'Website': '',
    'Contact Address ID': '1252231000038172750',
    'Billing Attention': '',
    'Billing Address': 'Flat No-30-28/1, Pandu Basti, SaiBaba Nagar,Jeedimetla',
    'Billing Street2': 'Quthbullapur,Medchal Malkajgiri',
    'Billing City': 'Hyderabad',
    'Billing State': 'Telangana',
    'Billing Country': 'India',
    'Billing Code': '500005',
    'Billing Phone': '',
    'Billing Fax': '',
    'Shipping Attention': '',
    'Shipping Address': 'Flat No-30-28/1, Pandu Basti, SaiBaba Nagar,Jeedimetla',
    'Shipping Street2': 'Quthbullapur,Medchal Malkajgiri',
    'Shipping City': 'Hyderabad',
    'Shipping State': 'Telangana',
    'Shipping Country': 'India',
    'Shipping Code': '500005',
    'Shipping Phone': '',
    'Shipping Fax': '',
    'Source': '1',
    'Last Sync Time': '',
    'Status': 'Active',
    'Primary Contact ID': '1252231000038172752',
    'Beneficiary Name': '',
    'Vendor Bank Account Number': '',
    'Vendor Bank Name': '',
    'Vendor Bank Code': '',
    'CF.CONTACT  ID': 'CON1690',
    'CF.CATEGORY': 'VENDORS-MACHINARY &EQUIPMENT',
    'CF.SALES PERSON NAME': 'SAI',
    'CF.SALES MANAGER': 'SAI',
  },
  {
    'Created Time': '2026-01-28 13:30:47',
    'Last Modified Time': '2026-01-28 13:30:47',
    'Contact ID': '1252231000038465658',
    'Source of Supply': 'TS',
    'Taxable': 'true',
    'Contact Name': 'Unique Glass Work & Solutions',
    'Display Name': 'Unique Glass Work & Solutions',
    'Company Name': 'Unique Glass Work & Solutions',
    'Salutation': '',
    'First Name': '',
    'Last Name': '',
    'EmailID': '',
    'Phone': '',
    'MobilePhone': '',
    'Skype Identity': '',
    'Facebook': '',
    'Twitter': '',
    'Department': '',
    'Designation': '',
    'Price List': '',
    'Currency Code': 'INR',
    'GST Treatment': 'business_none',
    'GST Identification Number (GSTIN)': '',
    'MSME/Udyam No': '',
    'MSME/Udyam Type': '',
    'Notes': '',
    'Website': '',
    'Contact Address ID': '1252231000038465658',
    'Billing Attention': '',
    'Billing Address': '',
    'Billing Street2': '',
    'Billing City': '',
    'Billing State': '',
    'Billing Country': '',
    'Billing Code': '',
    'Billing Phone': '',
    'Billing Fax': '',
    'Shipping Attention': '',
    'Shipping Address': '',
    'Shipping Street2': '',
    'Shipping City': '',
    'Shipping State': '',
    'Shipping Country': '',
    'Shipping Code': '',
    'Shipping Phone': '',
    'Shipping Fax': '',
    'Source': '1',
    'Last Sync Time': '',
    'Status': 'Active',
    'Primary Contact ID': '',
    'Beneficiary Name': 'Unique Glass Work & Solutions',
    'Vendor Bank Account Number': '32668371560',
    'Vendor Bank Name': 'State Bank of India',
    'Vendor Bank Code': 'SBIN0005094',
    'CF.CONTACT  ID': 'CON1692',
    'CF.CATEGORY': 'VENDORS- SERVICE&MAINTANANCE-UNITMANAGEMENT',
    'CF.SALES PERSON NAME': 'SAI',
    'CF.SALES MANAGER': 'SAI',
  },
  {
    'Created Time': '2026-01-30 13:01:16',
    'Last Modified Time': '2026-01-30 13:01:16',
    'Contact ID': '1252231000038560286',
    'Source of Supply': 'HR',
    'Taxable': 'true',
    'Contact Name': 'HEALTH Q LIFESCIENCES PRIVATE LIMITED',
    'Display Name': 'HEALTH Q LIFESCIENCES PRIVATE LIMITED',
    'Company Name': 'HEALTH Q LIFESCIENCES PRIVATE LIMITED',
    'Salutation': 'Dr.',
    'First Name': 'CHYTRA V',
    'Last Name': 'ANAND',
    'EmailID': 'noor.pasha@skinq.com',
    'Phone': '+91-8296603688',
    'MobilePhone': '',
    'Skype Identity': '',
    'Facebook': '',
    'Twitter': '',
    'Department': '',
    'Designation': '',
    'Price List': '',
    'Currency Code': 'INR',
    'GST Treatment': 'business_gst',
    'GST Identification Number (GSTIN)': '06AAFCH8713F2ZN',
    'MSME/Udyam No': '',
    'MSME/Udyam Type': '',
    'Notes': '',
    'Website': '',
    'Contact Address ID': '1252231000038560286',
    'Billing Attention': 'HealthQ Lifesciences Private Limited',
    'Billing Address': '2nd Floor, No.204, The Eva Mall, Brigade Road, \nBengaluru Urban',
    'Billing Street2': '',
    'Billing City': 'Bengaluru',
    'Billing State': 'Karnataka',
    'Billing Country': 'India',
    'Billing Code': '560025',
    'Billing Phone': '9254635671',
    'Billing Fax': '',
    'Shipping Attention': 'NOOR PASHA',
    'Shipping Address': '2nd Floor, No.204,',
    'Shipping Street2': 'The Eva Mall, Brigade Road',
    'Shipping City': 'Bengaluru, Bengaluru Urban',
    'Shipping State': 'Karnataka',
    'Shipping Country': 'India',
    'Shipping Code': '560025',
    'Shipping Phone': '8296603688',
    'Shipping Fax': '',
    'Source': '1',
    'Last Sync Time': '',
    'Status': 'Active',
    'Primary Contact ID': '1252231000038560288',
    'Beneficiary Name': '',
    'Vendor Bank Account Number': '',
    'Vendor Bank Name': '',
    'Vendor Bank Code': '',
    'CF.CONTACT  ID': 'CON1693',
    'CF.CATEGORY': 'CLIENTS-OFFLINE BRANDS',
    'CF.SALES PERSON NAME': 'MADHUPARNA',
    'CF.SALES MANAGER': 'SAI',
  },
  {
    'Created Time': '2026-02-02 19:12:58',
    'Last Modified Time': '2026-02-02 19:12:58',
    'Contact ID': '1252231000038679344',
    'Source of Supply': 'TS',
    'Taxable': 'true',
    'Contact Name': 'JORAUM SOLUTIONS PRIVATE LIMITED',
    'Display Name': 'JORAUM SOLUTIONS PRIVATE LIMITED',
    'Company Name': 'JORAUM SOLUTIONS PRIVATE LIMITED',
    'Salutation': '',
    'First Name': '',
    'Last Name': '',
    'EmailID': '',
    'Phone': '',
    'MobilePhone': '',
    'Skype Identity': '',
    'Facebook': '',
    'Twitter': '',
    'Department': '',
    'Designation': '',
    'Price List': '',
    'Currency Code': 'INR',
    'GST Treatment': 'business_gst',
    'GST Identification Number (GSTIN)': '36AAECJ6288N1ZT',
    'MSME/Udyam No': '',
    'MSME/Udyam Type': '',
    'Notes': '',
    'Website': '',
    'Contact Address ID': '1252231000038679344',
    'Billing Attention': '',
    'Billing Address': 'FLAT A24 401',
    'Billing Street2': 'SINGAPUR CITY, GHATKESAR',
    'Billing City': 'Hyderabad',
    'Billing State': 'Telangana',
    'Billing Country': 'India',
    'Billing Code': '500088',
    'Billing Phone': '',
    'Billing Fax': '',
    'Shipping Attention': '',
    'Shipping Address': 'FLAT A24 401',
    'Shipping Street2': 'SINGAPUR CITY, GHATKESAR',
    'Shipping City': 'Hyderabad',
    'Shipping State': 'Telangana',
    'Shipping Country': 'India',
    'Shipping Code': '500088',
    'Shipping Phone': '',
    'Shipping Fax': '',
    'Source': '1',
    'Last Sync Time': '',
    'Status': 'Active',
    'Primary Contact ID': '',
    'Beneficiary Name': '',
    'Vendor Bank Account Number': '',
    'Vendor Bank Name': '',
    'Vendor Bank Code': '',
    'CF.CONTACT  ID': 'CON1694',
    'CF.CATEGORY': 'VENDORS - DIRECT MARKETING (BRAND EI)',
    'CF.SALES PERSON NAME': 'SAI',
    'CF.SALES MANAGER': 'SAI',
  },
  {
    'Created Time': '2026-02-03 13:39:55',
    'Last Modified Time': '2026-02-03 13:39:55',
    'Contact ID': '1252231000038691902',
    'Source of Supply': 'UP',
    'Taxable': 'true',
    'Contact Name': 'CCFT LABORATORIES PRIVATE LIMITED',
    'Display Name': 'CCFT LABORATORIES PRIVATE LIMITED',
    'Company Name': 'CCFT LABORATORIES PRIVATE LIMITED',
    'Salutation': '',
    'First Name': '',
    'Last Name': '',
    'EmailID': 'tarushi@crueltyfreetesting.com',
    'Phone': '+91-92585 35734',
    'MobilePhone': '',
    'Skype Identity': '',
    'Facebook': '',
    'Twitter': '',
    'Department': '',
    'Designation': '',
    'Price List': '',
    'Currency Code': 'INR',
    'GST Treatment': 'business_gst',
    'GST Identification Number (GSTIN)': '09AAKCC4923B1ZU',
    'MSME/Udyam No': '',
    'MSME/Udyam Type': '',
    'Notes': '',
    'Website': '',
    'Contact Address ID': '1252231000038691902',
    'Billing Attention': 'CCFT LABORATORIES PRIVATE LIMITED',
    'Billing Address': 'Supplier of Services C-10/3, , Unnamed Road',
    'Billing Street2': 'Meerut',
    'Billing City': 'Meerut',
    'Billing State': 'Uttar Pradesh',
    'Billing Country': 'India',
    'Billing Code': '250002',
    'Billing Phone': '+91-92585 35734',
    'Billing Fax': '',
    'Shipping Attention': 'CCFT LABORATORIES PRIVATE LIMITED',
    'Shipping Address': 'Supplier of Services C-10/3, , Unnamed Road',
    'Shipping Street2': 'Meerut',
    'Shipping City': 'Meerut',
    'Shipping State': 'Uttar Pradesh',
    'Shipping Country': 'India',
    'Shipping Code': '250002',
    'Shipping Phone': '+91-92585 35734',
    'Shipping Fax': '',
    'Source': '1',
    'Last Sync Time': '',
    'Status': 'Active',
    'Primary Contact ID': '1252231000038691904',
    'Beneficiary Name': '',
    'Vendor Bank Account Number': '',
    'Vendor Bank Name': '',
    'Vendor Bank Code': '',
    'CF.CONTACT  ID': 'CON1695',
    'CF.CATEGORY': '',
    'CF.SALES PERSON NAME': 'SHIVAM PATHAK',
    'CF.SALES MANAGER': 'SHIVAM PATHAK',
  },
  {
    'Created Time': '2026-02-06 17:54:51',
    'Last Modified Time': '2026-02-09 13:13:12',
    'Contact ID': '1252231000038856121',
    'Source of Supply': 'TS',
    'Taxable': 'true',
    'Contact Name': 'VIVEKANANDA PRINTERS',
    'Display Name': 'VIVEKANANDA PRINTERS',
    'Company Name': 'VIVEKANANDA PRINTERS',
    'Salutation': '',
    'First Name': '',
    'Last Name': '',
    'EmailID': 'Marketing@vivekanandaprinters.com',
    'Phone': '+91-9392083487',
    'MobilePhone': '',
    'Skype Identity': '',
    'Facebook': '',
    'Twitter': '',
    'Department': '',
    'Designation': '',
    'Price List': '',
    'Currency Code': 'INR',
    'GST Treatment': 'business_gst',
    'GST Identification Number (GSTIN)': '36AALFV4539Q1Z8',
    'MSME/Udyam No': '',
    'MSME/Udyam Type': '',
    'Notes': '',
    'Website': '',
    'Contact Address ID': '1252231000038856121',
    'Billing Attention': 'VIVEKANANDA PRINTERS',
    'Billing Address': '2-158/11, Survey No 30,, , Suraram',
    'Billing Street2': 'Hyderabad',
    'Billing City': 'Medchal Malkajgiri',
    'Billing State': 'Telangana',
    'Billing Country': 'India',
    'Billing Code': '500055',
    'Billing Phone': '',
    'Billing Fax': '',
    'Shipping Attention': 'VIVEKANANDA PRINTERS',
    'Shipping Address': '2-158/11, Survey No 30,, , Suraram',
    'Shipping Street2': 'Hyderabad',
    'Shipping City': 'Medchal Malkajgiri',
    'Shipping State': 'Telangana',
    'Shipping Country': 'India',
    'Shipping Code': '500055',
    'Shipping Phone': '',
    'Shipping Fax': '',
    'Source': '1',
    'Last Sync Time': '',
    'Status': 'Active',
    'Primary Contact ID': '1252231000038856123',
    'Beneficiary Name': '',
    'Vendor Bank Account Number': '064025010000016',
    'Vendor Bank Name': 'UNION BANK',
    'Vendor Bank Code': 'UBIN0906409',
    'CF.CONTACT  ID': 'CON1696',
    'CF.CATEGORY': 'VENDORS - COGS-SECONDARY PACKAGING',
    'CF.SALES PERSON NAME': 'SAI',
    'CF.SALES MANAGER': 'SAI',
  },
  {
    'Created Time': '2026-02-09 16:25:47',
    'Last Modified Time': '2026-02-09 16:25:47',
    'Contact ID': '1252231000038903175',
    'Source of Supply': 'TS',
    'Taxable': 'true',
    'Contact Name': 'BEESHMA PEST CONTROL SERVICES',
    'Display Name': 'BEESHMA PEST CONTROL SERVICES',
    'Company Name': 'BEESHMA PEST CONTROL SERVICES',
    'Salutation': '',
    'First Name': '',
    'Last Name': '',
    'EmailID': 'beeshma.pestcontrol@gmail.com',
    'Phone': '+91-9390113521',
    'MobilePhone': '',
    'Skype Identity': '',
    'Facebook': '',
    'Twitter': '',
    'Department': '',
    'Designation': '',
    'Price List': '',
    'Currency Code': 'INR',
    'GST Treatment': 'business_gst',
    'GST Identification Number (GSTIN)': '36BJRPR5578P1ZU',
    'MSME/Udyam No': '',
    'MSME/Udyam Type': '',
    'Notes': '',
    'Website': '',
    'Contact Address ID': '1252231000038903175',
    'Billing Attention': 'BEESHMA PEST CONTROL SERVICES',
    'Billing Address': '2-2-647/182/A/6/3/A, , C.E COLONY',
    'Billing Street2': 'Hyderabad',
    'Billing City': 'Hyderabad',
    'Billing State': 'Telangana',
    'Billing Country': 'India',
    'Billing Code': '500013',
    'Billing Phone': '',
    'Billing Fax': '',
    'Shipping Attention': 'BEESHMA PEST CONTROL SERVICES',
    'Shipping Address': '2-2-647/182/A/6/3/A, , C.E COLONY',
    'Shipping Street2': 'Hyderabad',
    'Shipping City': 'Hyderabad',
    'Shipping State': 'Telangana',
    'Shipping Country': 'India',
    'Shipping Code': '500013',
    'Shipping Phone': '',
    'Shipping Fax': '',
    'Source': '1',
    'Last Sync Time': '',
    'Status': 'Active',
    'Primary Contact ID': '1252231000038903177',
    'Beneficiary Name': '',
    'Vendor Bank Account Number': '',
    'Vendor Bank Name': '',
    'Vendor Bank Code': '',
    'CF.CONTACT  ID': 'CON1697',
    'CF.CATEGORY': '',
    'CF.SALES PERSON NAME': 'SAI',
    'CF.SALES MANAGER': 'SAI',
  },
  {
    'Created Time': '2026-02-10 10:41:04',
    'Last Modified Time': '2026-02-10 10:41:04',
    'Contact ID': '1252231000038908573',
    'Source of Supply': 'TS',
    'Taxable': 'true',
    'Contact Name': 'SHRIJA PACK-TECH PRIVATE LIMITED',
    'Display Name': 'SHRIJA PACK-TECH PRIVATE LIMITED',
    'Company Name': 'SHRIJA PACK-TECH PRIVATE LIMITED',
    'Salutation': '',
    'First Name': '',
    'Last Name': '',
    'EmailID': 'naveenkumar@shrija.co.in',
    'Phone': '+91-8247008074',
    'MobilePhone': '',
    'Skype Identity': '',
    'Facebook': '',
    'Twitter': '',
    'Department': '',
    'Designation': '',
    'Price List': '',
    'Currency Code': 'INR',
    'GST Treatment': 'business_gst',
    'GST Identification Number (GSTIN)': '36ABMCS4921Q1ZK',
    'MSME/Udyam No': '',
    'MSME/Udyam Type': '',
    'Notes': '',
    'Website': '',
    'Contact Address ID': '1252231000038908573',
    'Billing Attention': '',
    'Billing Address': 'PLOT NO 108, 109 &114, 115, G1, BALAJI AAVAASA APARTMENTS, Pragathi Nagar Road',
    'Billing Street2': 'Hyderabad',
    'Billing City': 'Medchal Malkajgiri',
    'Billing State': 'Telangana',
    'Billing Country': 'India',
    'Billing Code': '500090',
    'Billing Phone': '',
    'Billing Fax': '',
    'Shipping Attention': '',
    'Shipping Address': 'PLOT NO 108, 109 &114, 115, G1, BALAJI AAVAASA APARTMENTS, Pragathi Nagar Road',
    'Shipping Street2': 'Hyderabad',
    'Shipping City': 'Medchal Malkajgiri',
    'Shipping State': 'Telangana',
    'Shipping Country': 'India',
    'Shipping Code': '500090',
    'Shipping Phone': '',
    'Shipping Fax': '',
    'Source': '1',
    'Last Sync Time': '',
    'Status': 'Active',
    'Primary Contact ID': '1252231000038908575',
    'Beneficiary Name': '',
    'Vendor Bank Account Number': '924020053344158',
    'Vendor Bank Name': '',
    'Vendor Bank Code': 'UTIB0002960',
    'CF.CONTACT  ID': 'CON1698',
    'CF.CATEGORY': 'VENDORS - COGS-SECONDARY PACKAGING',
    'CF.SALES PERSON NAME': 'SAI',
    'CF.SALES MANAGER': 'SAI',
  },
  {
    'Created Time': '2026-02-17 13:40:41',
    'Last Modified Time': '2026-02-17 13:40:41',
    'Contact ID': '1252231000039221077',
    'Source of Supply': 'KA',
    'Taxable': 'true',
    'Contact Name': 'HIRA HOLOVISION',
    'Display Name': 'HIRA HOLOVISION',
    'Company Name': 'HIRA HOLOVISION',
    'Salutation': '',
    'First Name': '',
    'Last Name': '',
    'EmailID': 'info@hiraholovision.com',
    'Phone': '+91-9986085690',
    'MobilePhone': '',
    'Skype Identity': '',
    'Facebook': '',
    'Twitter': '',
    'Department': '',
    'Designation': '',
    'Price List': '',
    'Currency Code': 'INR',
    'GST Treatment': 'business_gst',
    'GST Identification Number (GSTIN)': '29AKKPK4939J1ZJ',
    'MSME/Udyam No': '',
    'MSME/Udyam Type': '',
    'Notes': '',
    'Website': '',
    'Contact Address ID': '1252231000039221077',
    'Billing Attention': 'HIRA HOLOVISION',
    'Billing Address': '19, Arihant Towers, New Gudadhalli, Nehru Road, Mysore Road Cross,',
    'Billing Street2': 'Bengaluru',
    'Billing City': 'Bengaluru Urban',
    'Billing State': 'Karnataka',
    'Billing Country': 'India',
    'Billing Code': '560026',
    'Billing Phone': '+91-9986085690',
    'Billing Fax': '',
    'Shipping Attention': 'HIRA HOLOVISION',
    'Shipping Address': '19, Arihant Towers, New Gudadhalli, Nehru Road, Mysore Road Cross,',
    'Shipping Street2': 'Bengaluru',
    'Shipping City': 'Bengaluru Urban',
    'Shipping State': 'Karnataka',
    'Shipping Country': 'India',
    'Shipping Code': '560026',
    'Shipping Phone': '+91-9986085690',
    'Shipping Fax': '',
    'Source': '1',
    'Last Sync Time': '',
    'Status': 'Active',
    'Primary Contact ID': '1252231000039221079',
    'Beneficiary Name': 'HIRA HOLOVISION',
    'Vendor Bank Account Number': '625105040905',
    'Vendor Bank Name': 'ICICI BANK',
    'Vendor Bank Code': 'ICIC0006251',
    'CF.CONTACT  ID': 'CON1699',
    'CF.CATEGORY': 'VENDORS - COGS-SECONDARY PACKAGING',
    'CF.SALES PERSON NAME': 'SAI',
    'CF.SALES MANAGER': 'SAI',
  },
  {
    'Created Time': '2026-02-20 11:25:25',
    'Last Modified Time': '2026-02-20 11:25:25',
    'Contact ID': '1252231000039361026',
    'Source of Supply': 'TS',
    'Taxable': 'true',
    'Contact Name': 'Yes Bank Limited',
    'Display Name': 'Yes Bank Limited',
    'Company Name': 'Yes Bank Limited',
    'Salutation': '',
    'First Name': '',
    'Last Name': '',
    'EmailID': '',
    'Phone': '',
    'MobilePhone': '',
    'Skype Identity': '',
    'Facebook': '',
    'Twitter': '',
    'Department': '',
    'Designation': '',
    'Price List': '',
    'Currency Code': 'INR',
    'GST Treatment': 'business_gst',
    'GST Identification Number (GSTIN)': '36AAACY2068D1ZH',
    'MSME/Udyam No': '',
    'MSME/Udyam Type': '',
    'Notes': '',
    'Website': '',
    'Contact Address ID': '1252231000039361026',
    'Billing Attention': '',
    'Billing Address': '',
    'Billing Street2': '',
    'Billing City': '',
    'Billing State': '',
    'Billing Country': '',
    'Billing Code': '',
    'Billing Phone': '',
    'Billing Fax': '',
    'Shipping Attention': '',
    'Shipping Address': '',
    'Shipping Street2': '',
    'Shipping City': '',
    'Shipping State': '',
    'Shipping Country': '',
    'Shipping Code': '',
    'Shipping Phone': '',
    'Shipping Fax': '',
    'Source': '1',
    'Last Sync Time': '',
    'Status': 'Active',
    'Primary Contact ID': '',
    'Beneficiary Name': '',
    'Vendor Bank Account Number': '',
    'Vendor Bank Name': '',
    'Vendor Bank Code': '',
    'CF.CONTACT  ID': 'CON1701',
    'CF.CATEGORY': 'VENDORS-LOANS- NBFCS',
    'CF.SALES PERSON NAME': 'SAI',
    'CF.SALES MANAGER': 'SAI',
  },
  {
    'Created Time': '2026-02-20 12:29:42',
    'Last Modified Time': '2026-02-20 12:29:42',
    'Contact ID': '1252231000039364167',
    'Source of Supply': 'TS',
    'Taxable': 'true',
    'Contact Name': 'UGRO CAPITAL LIMITED',
    'Display Name': 'UGRO CAPITAL LIMITED',
    'Company Name': 'UGRO CAPITAL LIMITED',
    'Salutation': '',
    'First Name': '',
    'Last Name': '',
    'EmailID': '',
    'Phone': '',
    'MobilePhone': '',
    'Skype Identity': '',
    'Facebook': '',
    'Twitter': '',
    'Department': '',
    'Designation': '',
    'Price List': '',
    'Currency Code': 'INR',
    'GST Treatment': 'business_gst',
    'GST Identification Number (GSTIN)': '36AAACC2069E1Z0',
    'MSME/Udyam No': '',
    'MSME/Udyam Type': '',
    'Notes': '',
    'Website': '',
    'Contact Address ID': '1252231000039364167',
    'Billing Attention': '',
    'Billing Address': '',
    'Billing Street2': '',
    'Billing City': '',
    'Billing State': '',
    'Billing Country': '',
    'Billing Code': '',
    'Billing Phone': '',
    'Billing Fax': '',
    'Shipping Attention': '',
    'Shipping Address': '',
    'Shipping Street2': '',
    'Shipping City': '',
    'Shipping State': '',
    'Shipping Country': '',
    'Shipping Code': '',
    'Shipping Phone': '',
    'Shipping Fax': '',
    'Source': '1',
    'Last Sync Time': '',
    'Status': 'Active',
    'Primary Contact ID': '',
    'Beneficiary Name': '',
    'Vendor Bank Account Number': '',
    'Vendor Bank Name': '',
    'Vendor Bank Code': '',
    'CF.CONTACT  ID': 'CON1702',
    'CF.CATEGORY': 'VENDORS-LOANS- NBFCS',
    'CF.SALES PERSON NAME': 'SAI',
    'CF.SALES MANAGER': 'SAI',
  },
];
