const { DataTypes, Model } = require('sequelize');
const db = require('../../db');

/** Maps Excel/Zoho contact export row (header names) to DB column names (snake_case). */
function contactRowToVendor(row) {
  const map = {
    'Created Time': 'created_time',
    'Last Modified Time': 'last_modified_time',
    'Contact ID': 'contact_id',
    'Source of Supply': 'source_of_supply',
    'Taxable': 'taxable',
    'Contact Name': 'contact_name',
    'Display Name': 'display_name',
    'Company Name': 'company_name',
    'Salutation': 'salutation',
    'First Name': 'first_name',
    'Last Name': 'last_name',
    'EmailID': 'email_id',
    'Phone': 'phone',
    'MobilePhone': 'mobile_phone',
    'Skype Identity': 'skype_identity',
    'Facebook': 'facebook',
    'Twitter': 'twitter',
    'Department': 'department',
    'Designation': 'designation',
    'Price List': 'price_list',
    'Currency Code': 'currency_code',
    'GST Treatment': 'gst_treatment',
    'GST Identification Number (GSTIN)': 'gstin',
    'MSME/Udyam No': 'msme_udyam_no',
    'MSME/Udyam Type': 'msme_udyam_type',
    'Notes': 'notes',
    'Website': 'website',
    'Contact Address ID': 'contact_address_id',
    'Billing Attention': 'billing_attention',
    'Billing Address': 'billing_address',
    'Billing Street2': 'billing_street2',
    'Billing City': 'billing_city',
    'Billing State': 'billing_state',
    'Billing Country': 'billing_country',
    'Billing Code': 'billing_code',
    'Billing Phone': 'billing_phone',
    'Billing Fax': 'billing_fax',
    'Shipping Attention': 'shipping_attention',
    'Shipping Address': 'shipping_address',
    'Shipping Street2': 'shipping_street2',
    'Shipping City': 'shipping_city',
    'Shipping State': 'shipping_state',
    'Shipping Country': 'shipping_country',
    'Shipping Code': 'shipping_code',
    'Shipping Phone': 'shipping_phone',
    'Shipping Fax': 'shipping_fax',
    'Source': 'source',
    'Last Sync Time': 'last_sync_time',
    'Status': 'status',
    'Primary Contact ID': 'primary_contact_id',
    'Beneficiary Name': 'beneficiary_name',
    'Vendor Bank Account Number': 'vendor_bank_account_number',
    'Vendor Bank Name': 'vendor_bank_name',
    'Vendor Bank Code': 'vendor_bank_code',
    'CF.CONTACT  ID': 'cf_contact_id',
    'CF.CATEGORY': 'cf_category',
    'CF.SALES PERSON NAME': 'cf_sales_person_name',
    'CF.SALES MANAGER': 'cf_sales_manager',
  };
  const out = {};
  for (const [key, value] of Object.entries(row)) {
    const col = map[key];
    if (col) out[col] = value != null ? String(value) : '';
  }
  return out;
}

const stringCol = { type: DataTypes.STRING(500), allowNull: true };
const textCol = { type: DataTypes.TEXT, allowNull: true };

class Vendor extends Model {}

Vendor.init(
  {
    contact_id: { type: DataTypes.STRING(100), primaryKey: true, allowNull: false },
    created_time: stringCol,
    last_modified_time: stringCol,
    source_of_supply: stringCol,
    taxable: stringCol,
    contact_name: stringCol,
    display_name: stringCol,
    company_name: stringCol,
    salutation: stringCol,
    first_name: stringCol,
    last_name: stringCol,
    email_id: stringCol,
    phone: stringCol,
    mobile_phone: stringCol,
    skype_identity: stringCol,
    facebook: stringCol,
    twitter: stringCol,
    department: stringCol,
    designation: stringCol,
    price_list: stringCol,
    currency_code: stringCol,
    gst_treatment: stringCol,
    gstin: stringCol,
    msme_udyam_no: stringCol,
    msme_udyam_type: stringCol,
    notes: textCol,
    website: stringCol,
    contact_address_id: stringCol,
    billing_attention: stringCol,
    billing_address: textCol,
    billing_street2: stringCol,
    billing_city: stringCol,
    billing_state: stringCol,
    billing_country: stringCol,
    billing_code: stringCol,
    billing_phone: stringCol,
    billing_fax: stringCol,
    shipping_attention: stringCol,
    shipping_address: textCol,
    shipping_street2: stringCol,
    shipping_city: stringCol,
    shipping_state: stringCol,
    shipping_country: stringCol,
    shipping_code: stringCol,
    shipping_phone: stringCol,
    shipping_fax: stringCol,
    source: stringCol,
    last_sync_time: stringCol,
    status: stringCol,
    primary_contact_id: stringCol,
    beneficiary_name: stringCol,
    vendor_bank_account_number: stringCol,
    vendor_bank_name: stringCol,
    vendor_bank_code: stringCol,
    cf_contact_id: stringCol,
    cf_category: stringCol,
    cf_sales_person_name: stringCol,
    cf_sales_manager: stringCol,
  },
  {
    sequelize: db,
    modelName: 'Vendor',
    tableName: 'vendors',
    timestamps: false,
  }
);

module.exports = { Vendor, contactRowToVendor };
