/** Raw composite item rows from Excel/Zoho export. Keys match spreadsheet headers. */
module.exports = [
  {
    'Composite Item ID': '1252231000039513207',
    'Composite Item Name': "YplayZ SLIDE & GLIDE  YOU'RE THE ZEST 40ML",
    'Selling Price': 'INR 0.00',
    'Sales Description': '',
    'Product Type': 'goods',
    'Unit': 'NOS',
    'SKU': 'PR0006701',
    'UPC': '',
    'EAN': '',
    'ISBN': '',
    'Part Number': '',
    'HSN/SAC': '',
    'Purchase Price': 'INR 0.00',
    'Purchase Description': '',
    'Reorder Point': '',
    'Opening Stock': '0',
    'Opening Stock Value': 'INR 0.00',
    'Status': 'Active',
    'Sales Account': 'Sales',
    'Brand': '',
    'Manufacturer': '',
    'Package Weight': '0',
    'Package Length': '0',
    'Package Width': '0',
    'Package Height': '0',
    'Taxable': 'true',
    'Exemption Reason': '',
    'Taxability Type': '',
    'Category Name': '',
    'Purchase Account': 'Cost of Goods Sold',
    'Inventory Account': 'Finished Goods',
    'Inventory Valuation Method': 'fifo',
    'Preferred Vendor': '',
    'Source': '1',
    'Reference ID': '',
    'Last Sync Time': '',
    'Mapped Item Name': 'CUCUMBER PG EXTRACT - CLUB',
    'Mapped Item SKU': 'CLUB00023',
    'Mapped Quantity': '0.000400',
    'Combo Type': 'Assembly',
    'Intra State Tax Name': 'GST18',
    'Intra State Tax Rate': '18.000000',
    'Intra State Tax Type': 'Group',
    'Inter State Tax Name': 'IGST18',
    'Inter State Tax Rate': '18.000000',
    'Inter State Tax Type': 'Simple',
    'CF.ITEM CATEGORY': '',
    'CF.Material Code': '',
    'CF.Supplier': '',
    'CF.Method Of Preparation': '',
    'CF.PH': '',
    'CF.Viscosity': '',
    'CF.Fragrance': '',
    'CF.Texture': '',
    'CF.Appearance': '',
    'CF.DIS Number': '',
    'CF.Batch Number': '',
    'CF.Expiry Date': '',
    'CF.MFG Date': '',
    'CF.PACKAGING R&D POC': '',
    'CF.QUALITY TEAM POC': '',
    'CF.DESIGN TEAM POC': '',
    'CF.MRP': '',
    'CF.PRICE PER UNIT': '',
    'CF.MOQ': '',
    'CF.LEAD TIME': '0',
    'CF.CLIENT NAME': '',
    'CF.CONTACT ID': '',
    'CF.YIELD PERCENTAGE': '',
    'CF.TERGET DEVELOPMENT PRICE': '',
    'CF.PRICE PER KG': '',
    'CF.ITEM STATUS': '',
    'CF.MKT BRAND NAME': '',
    'CF.SALES PERSON NAME': '',
    'CF.OLD SKU': '',
    'CF.PREVIOUS SKU': '',
    'CF.INCI NAME': '',
    'CF.MONOCARTON STATUS': '',
    'CF.MONO CARTON PRICE': '',
    'CF.is_group_item': 'false',
  },
  {
    'Composite Item ID': '1252231000039513207',
    'Composite Item Name': "YplayZ SLIDE & GLIDE  YOU'RE THE ZEST 40ML",
    'Selling Price': 'INR 0.00',
    'Sales Description': '',
    'Product Type': 'goods',
    'Unit': 'NOS',
    'SKU': 'PR0006701',
    'UPC': '', 'EAN': '', 'ISBN': '', 'Part Number': '', 'HSN/SAC': '',
    'Purchase Price': 'INR 0.00',
    'Purchase Description': '',
    'Reorder Point': '',
    'Opening Stock': '0',
    'Opening Stock Value': 'INR 0.00',
    'Status': 'Active',
    'Sales Account': 'Sales',
    'Brand': '', 'Manufacturer': '',
    'Package Weight': '0', 'Package Length': '0', 'Package Width': '0', 'Package Height': '0',
    'Taxable': 'true', 'Exemption Reason': '', 'Taxability Type': '', 'Category Name': '',
    'Purchase Account': 'Cost of Goods Sold',
    'Inventory Account': 'Finished Goods',
    'Inventory Valuation Method': 'fifo',
    'Preferred Vendor': '',
    'Source': '1', 'Reference ID': '', 'Last Sync Time': '',
    'Mapped Item Name': 'TEGODEO HY 77',
    'Mapped Item SKU': '1000456',
    'Mapped Quantity': '0.000600',
    'Combo Type': 'Assembly',
    'Intra State Tax Name': 'GST18', 'Intra State Tax Rate': '18.000000', 'Intra State Tax Type': 'Group',
    'Inter State Tax Name': 'IGST18', 'Inter State Tax Rate': '18.000000', 'Inter State Tax Type': 'Simple',
    'CF.ITEM CATEGORY': '', 'CF.Material Code': '', 'CF.Supplier': '', 'CF.Method Of Preparation': '',
    'CF.PH': '', 'CF.Viscosity': '', 'CF.Fragrance': '', 'CF.Texture': '', 'CF.Appearance': '',
    'CF.DIS Number': '', 'CF.Batch Number': '', 'CF.Expiry Date': '', 'CF.MFG Date': '',
    'CF.PACKAGING R&D POC': '', 'CF.QUALITY TEAM POC': '', 'CF.DESIGN TEAM POC': '',
    'CF.MRP': '', 'CF.PRICE PER UNIT': '', 'CF.MOQ': '', 'CF.LEAD TIME': '0',
    'CF.CLIENT NAME': '', 'CF.CONTACT ID': '', 'CF.YIELD PERCENTAGE': '', 'CF.TERGET DEVELOPMENT PRICE': '', 'CF.PRICE PER KG': '', 'CF.ITEM STATUS': '',
    'CF.MKT BRAND NAME': '', 'CF.SALES PERSON NAME': '', 'CF.OLD SKU': '', 'CF.PREVIOUS SKU': '', 'CF.INCI NAME': '',
    'CF.MONOCARTON STATUS': '', 'CF.MONO CARTON PRICE': '', 'CF.is_group_item': 'false',
  },
  {
    'Composite Item ID': '1252231000039513207',
    'Composite Item Name': "YplayZ SLIDE & GLIDE  YOU'RE THE ZEST 40ML",
    'Selling Price': 'INR 0.00',
    'Sales Description': '',
    'Product Type': 'goods',
    'Unit': 'NOS',
    'SKU': 'PR0006701',
    'UPC': '', 'EAN': '', 'ISBN': '', 'Part Number': '', 'HSN/SAC': '',
    'Purchase Price': 'INR 0.00',
    'Purchase Description': '',
    'Reorder Point': '',
    'Opening Stock': '0',
    'Opening Stock Value': 'INR 0.00',
    'Status': 'Active',
    'Sales Account': 'Sales',
    'Brand': '', 'Manufacturer': '',
    'Package Weight': '0', 'Package Length': '0', 'Package Width': '0', 'Package Height': '0',
    'Taxable': 'true', 'Exemption Reason': '', 'Taxability Type': '', 'Category Name': '',
    'Purchase Account': 'Cost of Goods Sold',
    'Inventory Account': 'Finished Goods',
    'Inventory Valuation Method': 'fifo',
    'Preferred Vendor': '',
    'Source': '1', 'Reference ID': '', 'Last Sync Time': '',
    'Mapped Item Name': 'CALENDULA LIQUID EXTRACT',
    'Mapped Item SKU': '1000100',
    'Mapped Quantity': '0.000400',
    'Combo Type': 'Assembly',
    'Intra State Tax Name': 'GST18', 'Intra State Tax Rate': '18.000000', 'Intra State Tax Type': 'Group',
    'Inter State Tax Name': 'IGST18', 'Inter State Tax Rate': '18.000000', 'Inter State Tax Type': 'Simple',
    'CF.ITEM CATEGORY': '', 'CF.Material Code': '', 'CF.Supplier': '', 'CF.Method Of Preparation': '',
    'CF.PH': '', 'CF.Viscosity': '', 'CF.Fragrance': '', 'CF.Texture': '', 'CF.Appearance': '',
    'CF.DIS Number': '', 'CF.Batch Number': '', 'CF.Expiry Date': '', 'CF.MFG Date': '',
    'CF.PACKAGING R&D POC': '', 'CF.QUALITY TEAM POC': '', 'CF.DESIGN TEAM POC': '',
    'CF.MRP': '', 'CF.PRICE PER UNIT': '', 'CF.MOQ': '', 'CF.LEAD TIME': '0',
    'CF.CLIENT NAME': '', 'CF.CONTACT ID': '', 'CF.YIELD PERCENTAGE': '', 'CF.TERGET DEVELOPMENT PRICE': '', 'CF.PRICE PER KG': '', 'CF.ITEM STATUS': '',
    'CF.MKT BRAND NAME': '', 'CF.SALES PERSON NAME': '', 'CF.OLD SKU': '', 'CF.PREVIOUS SKU': '', 'CF.INCI NAME': '',
    'CF.MONOCARTON STATUS': '', 'CF.MONO CARTON PRICE': '', 'CF.is_group_item': 'false',
  },
  {
    'Composite Item ID': '1252231000039513207',
    'Composite Item Name': "YplayZ SLIDE & GLIDE  YOU'RE THE ZEST 40ML",
    'Selling Price': 'INR 0.00',
    'Sales Description': '',
    'Product Type': 'goods',
    'Unit': 'NOS',
    'SKU': 'PR0006701',
    'UPC': '', 'EAN': '', 'ISBN': '', 'Part Number': '', 'HSN/SAC': '',
    'Purchase Price': 'INR 0.00',
    'Purchase Description': '',
    'Reorder Point': '',
    'Opening Stock': '0',
    'Opening Stock Value': 'INR 0.00',
    'Status': 'Active',
    'Sales Account': 'Sales',
    'Brand': '', 'Manufacturer': '',
    'Package Weight': '0', 'Package Length': '0', 'Package Width': '0', 'Package Height': '0',
    'Taxable': 'true', 'Exemption Reason': '', 'Taxability Type': '', 'Category Name': '',
    'Purchase Account': 'Cost of Goods Sold',
    'Inventory Account': 'Finished Goods',
    'Inventory Valuation Method': 'fifo',
    'Preferred Vendor': '',
    'Source': '1', 'Reference ID': '', 'Last Sync Time': '',
    'Mapped Item Name': 'GRAPE SEED EXTRACT',
    'Mapped Item SKU': '1000212',
    'Mapped Quantity': '0.000400',
    'Combo Type': 'Assembly',
    'Intra State Tax Name': 'GST18', 'Intra State Tax Rate': '18.000000', 'Intra State Tax Type': 'Group',
    'Inter State Tax Name': 'IGST18', 'Inter State Tax Rate': '18.000000', 'Inter State Tax Type': 'Simple',
    'CF.ITEM CATEGORY': '', 'CF.Material Code': '', 'CF.Supplier': '', 'CF.Method Of Preparation': '',
    'CF.PH': '', 'CF.Viscosity': '', 'CF.Fragrance': '', 'CF.Texture': '', 'CF.Appearance': '',
    'CF.DIS Number': '', 'CF.Batch Number': '', 'CF.Expiry Date': '', 'CF.MFG Date': '',
    'CF.PACKAGING R&D POC': '', 'CF.QUALITY TEAM POC': '', 'CF.DESIGN TEAM POC': '',
    'CF.MRP': '', 'CF.PRICE PER UNIT': '', 'CF.MOQ': '', 'CF.LEAD TIME': '0',
    'CF.CLIENT NAME': '', 'CF.CONTACT ID': '', 'CF.YIELD PERCENTAGE': '', 'CF.TERGET DEVELOPMENT PRICE': '', 'CF.PRICE PER KG': '', 'CF.ITEM STATUS': '',
    'CF.MKT BRAND NAME': '', 'CF.SALES PERSON NAME': '', 'CF.OLD SKU': '', 'CF.PREVIOUS SKU': '', 'CF.INCI NAME': '',
    'CF.MONOCARTON STATUS': '', 'CF.MONO CARTON PRICE': '', 'CF.is_group_item': 'false',
  },
  {
    'Composite Item ID': '1252231000039513207',
    'Composite Item Name': "YplayZ SLIDE & GLIDE  YOU'RE THE ZEST 40ML",
    'Selling Price': 'INR 0.00',
    'Sales Description': '',
    'Product Type': 'goods',
    'Unit': 'NOS',
    'SKU': 'PR0006701',
    'UPC': '', 'EAN': '', 'ISBN': '', 'Part Number': '', 'HSN/SAC': '',
    'Purchase Price': 'INR 0.00',
    'Purchase Description': '',
    'Reorder Point': '',
    'Opening Stock': '0',
    'Opening Stock Value': 'INR 0.00',
    'Status': 'Active',
    'Sales Account': 'Sales',
    'Brand': '', 'Manufacturer': '',
    'Package Weight': '0', 'Package Length': '0', 'Package Width': '0', 'Package Height': '0',
    'Taxable': 'true', 'Exemption Reason': '', 'Taxability Type': '', 'Category Name': '',
    'Purchase Account': 'Cost of Goods Sold',
    'Inventory Account': 'Finished Goods',
    'Inventory Valuation Method': 'fifo',
    'Preferred Vendor': '',
    'Source': '1', 'Reference ID': '', 'Last Sync Time': '',
    'Mapped Item Name': 'WILLOW BARK EXTRACT',
    'Mapped Item SKU': '1000393',
    'Mapped Quantity': '0.000400',
    'Combo Type': 'Assembly',
    'Intra State Tax Name': 'GST18', 'Intra State Tax Rate': '18.000000', 'Intra State Tax Type': 'Group',
    'Inter State Tax Name': 'IGST18', 'Inter State Tax Rate': '18.000000', 'Inter State Tax Type': 'Simple',
    'CF.ITEM CATEGORY': '', 'CF.Material Code': '', 'CF.Supplier': '', 'CF.Method Of Preparation': '',
    'CF.PH': '', 'CF.Viscosity': '', 'CF.Fragrance': '', 'CF.Texture': '', 'CF.Appearance': '',
    'CF.DIS Number': '', 'CF.Batch Number': '', 'CF.Expiry Date': '', 'CF.MFG Date': '',
    'CF.PACKAGING R&D POC': '', 'CF.QUALITY TEAM POC': '', 'CF.DESIGN TEAM POC': '',
    'CF.MRP': '', 'CF.PRICE PER UNIT': '', 'CF.MOQ': '', 'CF.LEAD TIME': '0',
    'CF.CLIENT NAME': '', 'CF.CONTACT ID': '', 'CF.YIELD PERCENTAGE': '', 'CF.TERGET DEVELOPMENT PRICE': '', 'CF.PRICE PER KG': '', 'CF.ITEM STATUS': '',
    'CF.MKT BRAND NAME': '', 'CF.SALES PERSON NAME': '', 'CF.OLD SKU': '', 'CF.PREVIOUS SKU': '', 'CF.INCI NAME': '',
    'CF.MONOCARTON STATUS': '', 'CF.MONO CARTON PRICE': '', 'CF.is_group_item': 'false',
  },
  {
    'Composite Item ID': '1252231000039513207',
    'Composite Item Name': "YplayZ SLIDE & GLIDE  YOU'RE THE ZEST 40ML",
    'Selling Price': 'INR 0.00',
    'Sales Description': '',
    'Product Type': 'goods',
    'Unit': 'NOS',
    'SKU': 'PR0006701',
    'UPC': '', 'EAN': '', 'ISBN': '', 'Part Number': '', 'HSN/SAC': '',
    'Purchase Price': 'INR 0.00',
    'Purchase Description': '',
    'Reorder Point': '',
    'Opening Stock': '0',
    'Opening Stock Value': 'INR 0.00',
    'Status': 'Active',
    'Sales Account': 'Sales',
    'Brand': '', 'Manufacturer': '',
    'Package Weight': '0', 'Package Length': '0', 'Package Width': '0', 'Package Height': '0',
    'Taxable': 'true', 'Exemption Reason': '', 'Taxability Type': '', 'Category Name': '',
    'Purchase Account': 'Cost of Goods Sold',
    'Inventory Account': 'Finished Goods',
    'Inventory Valuation Method': 'fifo',
    'Preferred Vendor': '',
    'Source': '1', 'Reference ID': '', 'Last Sync Time': '',
    'Mapped Item Name': 'PROBACILLUS REVIVE',
    'Mapped Item SKU': '1000573',
    'Mapped Quantity': '0.000400',
    'Combo Type': 'Assembly',
    'Intra State Tax Name': 'GST18', 'Intra State Tax Rate': '18.000000', 'Intra State Tax Type': 'Group',
    'Inter State Tax Name': 'IGST18', 'Inter State Tax Rate': '18.000000', 'Inter State Tax Type': 'Simple',
    'CF.ITEM CATEGORY': '', 'CF.Material Code': '', 'CF.Supplier': '', 'CF.Method Of Preparation': '',
    'CF.PH': '', 'CF.Viscosity': '', 'CF.Fragrance': '', 'CF.Texture': '', 'CF.Appearance': '',
    'CF.DIS Number': '', 'CF.Batch Number': '', 'CF.Expiry Date': '', 'CF.MFG Date': '',
    'CF.PACKAGING R&D POC': '', 'CF.QUALITY TEAM POC': '', 'CF.DESIGN TEAM POC': '',
    'CF.MRP': '', 'CF.PRICE PER UNIT': '', 'CF.MOQ': '', 'CF.LEAD TIME': '0',
    'CF.CLIENT NAME': '', 'CF.CONTACT ID': '', 'CF.YIELD PERCENTAGE': '', 'CF.TERGET DEVELOPMENT PRICE': '', 'CF.PRICE PER KG': '', 'CF.ITEM STATUS': '',
    'CF.MKT BRAND NAME': '', 'CF.SALES PERSON NAME': '', 'CF.OLD SKU': '', 'CF.PREVIOUS SKU': '', 'CF.INCI NAME': '',
    'CF.MONOCARTON STATUS': '', 'CF.MONO CARTON PRICE': '', 'CF.is_group_item': 'false',
  },
  {
    'Composite Item ID': '1252231000039513207',
    'Composite Item Name': "YplayZ SLIDE & GLIDE  YOU'RE THE ZEST 40ML",
    'Selling Price': 'INR 0.00',
    'Sales Description': '',
    'Product Type': 'goods',
    'Unit': 'NOS',
    'SKU': 'PR0006701',
    'UPC': '', 'EAN': '', 'ISBN': '', 'Part Number': '', 'HSN/SAC': '',
    'Purchase Price': 'INR 0.00',
    'Purchase Description': '',
    'Reorder Point': '',
    'Opening Stock': '0',
    'Opening Stock Value': 'INR 0.00',
    'Status': 'Active',
    'Sales Account': 'Sales',
    'Brand': '', 'Manufacturer': '',
    'Package Weight': '0', 'Package Length': '0', 'Package Width': '0', 'Package Height': '0',
    'Taxable': 'true', 'Exemption Reason': '', 'Taxability Type': '', 'Category Name': '',
    'Purchase Account': 'Cost of Goods Sold',
    'Inventory Account': 'Finished Goods',
    'Inventory Valuation Method': 'fifo',
    'Preferred Vendor': '',
    'Source': '1', 'Reference ID': '', 'Last Sync Time': '',
    'Mapped Item Name': 'PRESERVATIVE CLUB',
    'Mapped Item SKU': 'CLUB00038',
    'Mapped Quantity': '0.000200',
    'Combo Type': 'Assembly',
    'Intra State Tax Name': 'GST18', 'Intra State Tax Rate': '18.000000', 'Intra State Tax Type': 'Group',
    'Inter State Tax Name': 'IGST18', 'Inter State Tax Rate': '18.000000', 'Inter State Tax Type': 'Simple',
    'CF.ITEM CATEGORY': '', 'CF.Material Code': '', 'CF.Supplier': '', 'CF.Method Of Preparation': '',
    'CF.PH': '', 'CF.Viscosity': '', 'CF.Fragrance': '', 'CF.Texture': '', 'CF.Appearance': '',
    'CF.DIS Number': '', 'CF.Batch Number': '', 'CF.Expiry Date': '', 'CF.MFG Date': '',
    'CF.PACKAGING R&D POC': '', 'CF.QUALITY TEAM POC': '', 'CF.DESIGN TEAM POC': '',
    'CF.MRP': '', 'CF.PRICE PER UNIT': '', 'CF.MOQ': '', 'CF.LEAD TIME': '0',
    'CF.CLIENT NAME': '', 'CF.CONTACT ID': '', 'CF.YIELD PERCENTAGE': '', 'CF.TERGET DEVELOPMENT PRICE': '', 'CF.PRICE PER KG': '', 'CF.ITEM STATUS': '',
    'CF.MKT BRAND NAME': '', 'CF.SALES PERSON NAME': '', 'CF.OLD SKU': '', 'CF.PREVIOUS SKU': '', 'CF.INCI NAME': '',
    'CF.MONOCARTON STATUS': '', 'CF.MONO CARTON PRICE': '', 'CF.is_group_item': 'false',
  },
  {
    'Composite Item ID': '1252231000039513207',
    'Composite Item Name': "YplayZ SLIDE & GLIDE  YOU'RE THE ZEST 40ML",
    'Selling Price': 'INR 0.00',
    'Sales Description': '',
    'Product Type': 'goods',
    'Unit': 'NOS',
    'SKU': 'PR0006701',
    'UPC': '', 'EAN': '', 'ISBN': '', 'Part Number': '', 'HSN/SAC': '',
    'Purchase Price': 'INR 0.00',
    'Purchase Description': '',
    'Reorder Point': '',
    'Opening Stock': '0',
    'Opening Stock Value': 'INR 0.00',
    'Status': 'Active',
    'Sales Account': 'Sales',
    'Brand': '', 'Manufacturer': '',
    'Package Weight': '0', 'Package Length': '0', 'Package Width': '0', 'Package Height': '0',
    'Taxable': 'true', 'Exemption Reason': '', 'Taxability Type': '', 'Category Name': '',
    'Purchase Account': 'Cost of Goods Sold',
    'Inventory Account': 'Finished Goods',
    'Inventory Valuation Method': 'fifo',
    'Preferred Vendor': '',
    'Source': '1', 'Reference ID': '', 'Last Sync Time': '',
    'Mapped Item Name': 'WITCH HAZEL WITH BENZOIC ACID',
    'Mapped Item SKU': '1000487',
    'Mapped Quantity': '0.000200',
    'Combo Type': 'Assembly',
    'Intra State Tax Name': 'GST18', 'Intra State Tax Rate': '18.000000', 'Intra State Tax Type': 'Group',
    'Inter State Tax Name': 'IGST18', 'Inter State Tax Rate': '18.000000', 'Inter State Tax Type': 'Simple',
    'CF.ITEM CATEGORY': '', 'CF.Material Code': '', 'CF.Supplier': '', 'CF.Method Of Preparation': '',
    'CF.PH': '', 'CF.Viscosity': '', 'CF.Fragrance': '', 'CF.Texture': '', 'CF.Appearance': '',
    'CF.DIS Number': '', 'CF.Batch Number': '', 'CF.Expiry Date': '', 'CF.MFG Date': '',
    'CF.PACKAGING R&D POC': '', 'CF.QUALITY TEAM POC': '', 'CF.DESIGN TEAM POC': '',
    'CF.MRP': '', 'CF.PRICE PER UNIT': '', 'CF.MOQ': '', 'CF.LEAD TIME': '0',
    'CF.CLIENT NAME': '', 'CF.CONTACT ID': '', 'CF.YIELD PERCENTAGE': '', 'CF.TERGET DEVELOPMENT PRICE': '', 'CF.PRICE PER KG': '', 'CF.ITEM STATUS': '',
    'CF.MKT BRAND NAME': '', 'CF.SALES PERSON NAME': '', 'CF.OLD SKU': '', 'CF.PREVIOUS SKU': '', 'CF.INCI NAME': '',
    'CF.MONOCARTON STATUS': '', 'CF.MONO CARTON PRICE': '', 'CF.is_group_item': 'false',
  },
  {
    'Composite Item ID': '1252231000039513207',
    'Composite Item Name': "YplayZ SLIDE & GLIDE  YOU'RE THE ZEST 40ML",
    'Selling Price': 'INR 0.00',
    'Sales Description': '',
    'Product Type': 'goods',
    'Unit': 'NOS',
    'SKU': 'PR0006701',
    'UPC': '', 'EAN': '', 'ISBN': '', 'Part Number': '', 'HSN/SAC': '',
    'Purchase Price': 'INR 0.00',
    'Purchase Description': '',
    'Reorder Point': '',
    'Opening Stock': '0',
    'Opening Stock Value': 'INR 0.00',
    'Status': 'Active',
    'Sales Account': 'Sales',
    'Brand': '', 'Manufacturer': '',
    'Package Weight': '0', 'Package Length': '0', 'Package Width': '0', 'Package Height': '0',
    'Taxable': 'true', 'Exemption Reason': '', 'Taxability Type': '', 'Category Name': '',
    'Purchase Account': 'Cost of Goods Sold',
    'Inventory Account': 'Finished Goods',
    'Inventory Valuation Method': 'fifo',
    'Preferred Vendor': '',
    'Source': '1', 'Reference ID': '', 'Last Sync Time': '',
    'Mapped Item Name': 'SODIUM GLUCONATE',
    'Mapped Item SKU': '1000422',
    'Mapped Quantity': '0.000080',
    'Combo Type': 'Assembly',
    'Intra State Tax Name': 'GST18', 'Intra State Tax Rate': '18.000000', 'Intra State Tax Type': 'Group',
    'Inter State Tax Name': 'IGST18', 'Inter State Tax Rate': '18.000000', 'Inter State Tax Type': 'Simple',
    'CF.ITEM CATEGORY': '', 'CF.Material Code': '', 'CF.Supplier': '', 'CF.Method Of Preparation': '',
    'CF.PH': '', 'CF.Viscosity': '', 'CF.Fragrance': '', 'CF.Texture': '', 'CF.Appearance': '',
    'CF.DIS Number': '', 'CF.Batch Number': '', 'CF.Expiry Date': '', 'CF.MFG Date': '',
    'CF.PACKAGING R&D POC': '', 'CF.QUALITY TEAM POC': '', 'CF.DESIGN TEAM POC': '',
    'CF.MRP': '', 'CF.PRICE PER UNIT': '', 'CF.MOQ': '', 'CF.LEAD TIME': '0',
    'CF.CLIENT NAME': '', 'CF.CONTACT ID': '', 'CF.YIELD PERCENTAGE': '', 'CF.TERGET DEVELOPMENT PRICE': '', 'CF.PRICE PER KG': '', 'CF.ITEM STATUS': '',
    'CF.MKT BRAND NAME': '', 'CF.SALES PERSON NAME': '', 'CF.OLD SKU': '', 'CF.PREVIOUS SKU': '', 'CF.INCI NAME': '',
    'CF.MONOCARTON STATUS': '', 'CF.MONO CARTON PRICE': '', 'CF.is_group_item': 'false',
  },
  {
    'Composite Item ID': '1252231000039513207',
    'Composite Item Name': "YplayZ SLIDE & GLIDE  YOU'RE THE ZEST 40ML",
    'Selling Price': 'INR 0.00',
    'Sales Description': '',
    'Product Type': 'goods',
    'Unit': 'NOS',
    'SKU': 'PR0006701',
    'UPC': '', 'EAN': '', 'ISBN': '', 'Part Number': '', 'HSN/SAC': '',
    'Purchase Price': 'INR 0.00',
    'Purchase Description': '',
    'Reorder Point': '',
    'Opening Stock': '0',
    'Opening Stock Value': 'INR 0.00',
    'Status': 'Active',
    'Sales Account': 'Sales',
    'Brand': '', 'Manufacturer': '',
    'Package Weight': '0', 'Package Length': '0', 'Package Width': '0', 'Package Height': '0',
    'Taxable': 'true', 'Exemption Reason': '', 'Taxability Type': '', 'Category Name': '',
    'Purchase Account': 'Cost of Goods Sold',
    'Inventory Account': 'Finished Goods',
    'Inventory Valuation Method': 'fifo',
    'Preferred Vendor': '',
    'Source': '1', 'Reference ID': '', 'Last Sync Time': '',
    'Mapped Item Name': 'PURAC HS 88',
    'Mapped Item SKU': '1000255',
    'Mapped Quantity': '0.000120',
    'Combo Type': 'Assembly',
    'Intra State Tax Name': 'GST18', 'Intra State Tax Rate': '18.000000', 'Intra State Tax Type': 'Group',
    'Inter State Tax Name': 'IGST18', 'Inter State Tax Rate': '18.000000', 'Inter State Tax Type': 'Simple',
    'CF.ITEM CATEGORY': '', 'CF.Material Code': '', 'CF.Supplier': '', 'CF.Method Of Preparation': '',
    'CF.PH': '', 'CF.Viscosity': '', 'CF.Fragrance': '', 'CF.Texture': '', 'CF.Appearance': '',
    'CF.DIS Number': '', 'CF.Batch Number': '', 'CF.Expiry Date': '', 'CF.MFG Date': '',
    'CF.PACKAGING R&D POC': '', 'CF.QUALITY TEAM POC': '', 'CF.DESIGN TEAM POC': '',
    'CF.MRP': '', 'CF.PRICE PER UNIT': '', 'CF.MOQ': '', 'CF.LEAD TIME': '0',
    'CF.CLIENT NAME': '', 'CF.CONTACT ID': '', 'CF.YIELD PERCENTAGE': '', 'CF.TERGET DEVELOPMENT PRICE': '', 'CF.PRICE PER KG': '', 'CF.ITEM STATUS': '',
    'CF.MKT BRAND NAME': '', 'CF.SALES PERSON NAME': '', 'CF.OLD SKU': '', 'CF.PREVIOUS SKU': '', 'CF.INCI NAME': '',
    'CF.MONOCARTON STATUS': '', 'CF.MONO CARTON PRICE': '', 'CF.is_group_item': 'false',
  },
  {
    'Composite Item ID': '1252231000039513207',
    'Composite Item Name': "YplayZ SLIDE & GLIDE  YOU'RE THE ZEST 40ML",
    'Selling Price': 'INR 0.00',
    'Sales Description': '',
    'Product Type': 'goods',
    'Unit': 'NOS',
    'SKU': 'PR0006701',
    'UPC': '', 'EAN': '', 'ISBN': '', 'Part Number': '', 'HSN/SAC': '',
    'Purchase Price': 'INR 0.00',
    'Purchase Description': '',
    'Reorder Point': '',
    'Opening Stock': '0',
    'Opening Stock Value': 'INR 0.00',
    'Status': 'Active',
    'Sales Account': 'Sales',
    'Brand': '', 'Manufacturer': '',
    'Package Weight': '0', 'Package Length': '0', 'Package Width': '0', 'Package Height': '0',
    'Taxable': 'true', 'Exemption Reason': '', 'Taxability Type': '', 'Category Name': '',
    'Purchase Account': 'Cost of Goods Sold',
    'Inventory Account': 'Finished Goods',
    'Inventory Valuation Method': 'fifo',
    'Preferred Vendor': '',
    'Source': '1', 'Reference ID': '', 'Last Sync Time': '',
    'Mapped Item Name': 'SODIUM HYALURONATE - CLUB',
    'Mapped Item SKU': 'CLUB00028',
    'Mapped Quantity': '0.000004',
    'Combo Type': 'Assembly',
    'Intra State Tax Name': 'GST18', 'Intra State Tax Rate': '18.000000', 'Intra State Tax Type': 'Group',
    'Inter State Tax Name': 'IGST18', 'Inter State Tax Rate': '18.000000', 'Inter State Tax Type': 'Simple',
    'CF.ITEM CATEGORY': '', 'CF.Material Code': '', 'CF.Supplier': '', 'CF.Method Of Preparation': '',
    'CF.PH': '', 'CF.Viscosity': '', 'CF.Fragrance': '', 'CF.Texture': '', 'CF.Appearance': '',
    'CF.DIS Number': '', 'CF.Batch Number': '', 'CF.Expiry Date': '', 'CF.MFG Date': '',
    'CF.PACKAGING R&D POC': '', 'CF.QUALITY TEAM POC': '', 'CF.DESIGN TEAM POC': '',
    'CF.MRP': '', 'CF.PRICE PER UNIT': '', 'CF.MOQ': '', 'CF.LEAD TIME': '0',
    'CF.CLIENT NAME': '', 'CF.CONTACT ID': '', 'CF.YIELD PERCENTAGE': '', 'CF.TERGET DEVELOPMENT PRICE': '', 'CF.PRICE PER KG': '', 'CF.ITEM STATUS': '',
    'CF.MKT BRAND NAME': '', 'CF.SALES PERSON NAME': '', 'CF.OLD SKU': '', 'CF.PREVIOUS SKU': '', 'CF.INCI NAME': '',
    'CF.MONOCARTON STATUS': '', 'CF.MONO CARTON PRICE': '', 'CF.is_group_item': 'false',
  },
  {
    'Composite Item ID': '1252231000039513207',
    'Composite Item Name': "YplayZ SLIDE & GLIDE  YOU'RE THE ZEST 40ML",
    'Selling Price': 'INR 0.00',
    'Sales Description': '',
    'Product Type': 'goods',
    'Unit': 'NOS',
    'SKU': 'PR0006701',
    'UPC': '', 'EAN': '', 'ISBN': '', 'Part Number': '', 'HSN/SAC': '',
    'Purchase Price': 'INR 0.00',
    'Purchase Description': '',
    'Reorder Point': '',
    'Opening Stock': '0',
    'Opening Stock Value': 'INR 0.00',
    'Status': 'Active',
    'Sales Account': 'Sales',
    'Brand': '', 'Manufacturer': '',
    'Package Weight': '0', 'Package Length': '0', 'Package Width': '0', 'Package Height': '0',
    'Taxable': 'true', 'Exemption Reason': '', 'Taxability Type': '', 'Category Name': '',
    'Purchase Account': 'Cost of Goods Sold',
    'Inventory Account': 'Finished Goods',
    'Inventory Valuation Method': 'fifo',
    'Preferred Vendor': '',
    'Source': '1', 'Reference ID': '', 'Last Sync Time': '',
    'Mapped Item Name': 'CHANNEL ALLURE SPORTS HOMME COMM FRAGRANCE',
    'Mapped Item SKU': '2000160',
    'Mapped Quantity': '0.003200',
    'Combo Type': 'Assembly',
    'Intra State Tax Name': 'GST18', 'Intra State Tax Rate': '18.000000', 'Intra State Tax Type': 'Group',
    'Inter State Tax Name': 'IGST18', 'Inter State Tax Rate': '18.000000', 'Inter State Tax Type': 'Simple',
    'CF.ITEM CATEGORY': '', 'CF.Material Code': '', 'CF.Supplier': '', 'CF.Method Of Preparation': '',
    'CF.PH': '', 'CF.Viscosity': '', 'CF.Fragrance': '', 'CF.Texture': '', 'CF.Appearance': '',
    'CF.DIS Number': '', 'CF.Batch Number': '', 'CF.Expiry Date': '', 'CF.MFG Date': '',
    'CF.PACKAGING R&D POC': '', 'CF.QUALITY TEAM POC': '', 'CF.DESIGN TEAM POC': '',
    'CF.MRP': '', 'CF.PRICE PER UNIT': '', 'CF.MOQ': '', 'CF.LEAD TIME': '0',
    'CF.CLIENT NAME': '', 'CF.CONTACT ID': '', 'CF.YIELD PERCENTAGE': '', 'CF.TERGET DEVELOPMENT PRICE': '', 'CF.PRICE PER KG': '', 'CF.ITEM STATUS': '',
    'CF.MKT BRAND NAME': '', 'CF.SALES PERSON NAME': '', 'CF.OLD SKU': '', 'CF.PREVIOUS SKU': '', 'CF.INCI NAME': '',
    'CF.MONOCARTON STATUS': '', 'CF.MONO CARTON PRICE': '', 'CF.is_group_item': 'false',
  },
];
