/**
 * Canonical rows for `customization_packaging_options`.
 * Shared by `seed.js` (full reseed) and server bootstrap when the table has no rows.
 */
module.exports = [
  {
    option_id: 'bottle_30ml_dropper',
    title: '30 ml',
    subtitle: 'Glass / PP · dropper',
    review_label: '30 ml dropper bottle',
    sku_code: 'EI-PK-30-DP',
    is_custom: false,
    sort_order: 10,
    active: true,
    specs: {
      skuVol: '30 ml',
      material: 'Glass / PP',
      color: 'Frosted clear / White',
      pantone: '—',
      dispensing: 'Glass dropper 0.6 ml',
      pumpMaterial: 'Glass / PE',
      pumpColor: 'Clear / White',
      capMaterial: 'PP',
      capColor: 'White',
      moq: 100,
    },
  },
  {
    option_id: 'bottle_50ml_pump',
    title: '50 ml',
    subtitle: 'Airless-style pump',
    review_label: '50 ml pump bottle',
    sku_code: 'EI-PK-50-PMP',
    is_custom: false,
    sort_order: 20,
    active: true,
    specs: {
      skuVol: '50 ml',
      material: 'PP / PET',
      color: 'White / Natural',
      pantone: 'Custom on request',
      dispensing: '0.2 ml / stroke',
      pumpMaterial: 'PP',
      pumpColor: 'White',
      capMaterial: 'PP overcap',
      capColor: 'White',
      moq: 100,
    },
  },
  {
    option_id: 'bottle_100ml_pump',
    title: '100 ml',
    subtitle: 'Treatment pump',
    review_label: '100 ml pump bottle',
    sku_code: 'EI-PK-100-PMP',
    is_custom: false,
    sort_order: 30,
    active: true,
    specs: {
      skuVol: '100 ml',
      material: 'PET / PP',
      color: 'White',
      pantone: '—',
      dispensing: '0.25 ml / stroke',
      pumpMaterial: 'PP',
      pumpColor: 'White',
      capMaterial: 'PP',
      capColor: 'White',
      moq: 100,
    },
  },
  {
    option_id: 'airless_15ml',
    title: '15 ml',
    subtitle: 'Airless pump',
    review_label: '15 ml airless',
    sku_code: 'EI-PK-15-AL',
    is_custom: false,
    sort_order: 40,
    active: true,
    specs: {
      skuVol: '15 ml',
      material: 'PP / AS',
      color: 'White / Silver collar',
      pantone: '—',
      dispensing: '0.15 ml / stroke',
      pumpMaterial: 'PP',
      pumpColor: 'White',
      capMaterial: 'PP',
      capColor: 'White',
      moq: 200,
    },
  },
  {
    option_id: 'airless_30ml',
    title: '30 ml',
    subtitle: 'Airless pump',
    review_label: '30 ml airless',
    sku_code: 'EI-PK-30-AL',
    is_custom: false,
    sort_order: 50,
    active: true,
    specs: {
      skuVol: '30 ml',
      material: 'PP / AS',
      color: 'White / Silver collar',
      pantone: '—',
      dispensing: '0.2 ml / stroke',
      pumpMaterial: 'PP',
      pumpColor: 'White',
      capMaterial: 'PP',
      capColor: 'White',
      moq: 200,
    },
  },
  {
    option_id: 'jar_30g',
    title: '30 g',
    subtitle: 'Cream jar · double-wall',
    review_label: '30 g cream jar',
    sku_code: 'EI-PK-30-JR',
    is_custom: false,
    sort_order: 60,
    active: true,
    specs: {
      skuVol: '30 g',
      material: 'PP / PET',
      color: 'White',
      pantone: '—',
      dispensing: '—',
      pumpMaterial: '—',
      pumpColor: '—',
      capMaterial: 'PP',
      capColor: 'White',
      moq: 150,
    },
  },
  {
    option_id: 'jar_50g',
    title: '50 g',
    subtitle: 'Cream jar',
    review_label: '50 g cream jar',
    sku_code: 'EI-PK-50-JR',
    is_custom: false,
    sort_order: 70,
    active: true,
    specs: {
      skuVol: '50 g',
      material: 'PP / Glass',
      color: 'White / Clear',
      pantone: '—',
      dispensing: '—',
      pumpMaterial: '—',
      pumpColor: '—',
      capMaterial: 'PP',
      capColor: 'White',
      moq: 150,
    },
  },
  {
    option_id: 'tube_50ml',
    title: '50 ml',
    subtitle: 'Laminate tube',
    review_label: '50 ml tube',
    sku_code: 'EI-PK-50-TB',
    is_custom: false,
    sort_order: 80,
    active: true,
    specs: {
      skuVol: '50 ml',
      material: 'ABL / PE',
      color: 'White',
      pantone: 'Print artwork',
      dispensing: 'Flip-top / screw cap',
      pumpMaterial: 'PE',
      pumpColor: 'White',
      capMaterial: 'PP',
      capColor: 'White',
      moq: 300,
    },
  },
  {
    option_id: 'tube_100ml',
    title: '100 ml',
    subtitle: 'Laminate tube',
    review_label: '100 ml tube',
    sku_code: 'EI-PK-100-TB',
    is_custom: false,
    sort_order: 90,
    active: true,
    specs: {
      skuVol: '100 ml',
      material: 'ABL / PE',
      color: 'White',
      pantone: 'Print artwork',
      dispensing: 'Flip-top',
      pumpMaterial: 'PE',
      pumpColor: 'White',
      capMaterial: 'PP',
      capColor: 'White',
      moq: 300,
    },
  },
  {
    option_id: 'spray_100ml',
    title: '100 ml',
    subtitle: 'Fine mist spray',
    review_label: '100 ml spray bottle',
    sku_code: 'EI-PK-100-SPR',
    is_custom: false,
    sort_order: 100,
    active: true,
    specs: {
      skuVol: '100 ml',
      material: 'PET / PP',
      color: 'Clear / White',
      pantone: '—',
      dispensing: 'Fine mist 0.12 ml',
      pumpMaterial: 'PP',
      pumpColor: 'White',
      capMaterial: 'PP',
      capColor: 'Clear hood',
      moq: 150,
    },
  },
  {
    option_id: 'custom',
    title: 'Custom',
    subtitle: 'Upload your own pack specs',
    review_label: 'Custom packaging (upload / brief)',
    sku_code: 'CUSTOM',
    is_custom: true,
    sort_order: 1000,
    active: true,
    specs: {
      skuVol: '—',
      material: 'Per your brief',
      color: '—',
      pantone: '—',
      dispensing: '—',
      pumpMaterial: '—',
      pumpColor: '—',
      capMaterial: '—',
      capColor: '—',
      moq: 0,
    },
  },
];
