/** Legacy appointment rows imported from external system. */
module.exports = [
  {
    app_id: '1',
    app_type: 'NULL',
    app_doc_name: 'shiva',
    app_doc_mobile: '9703022266',
    app_doc_email: 'shivam@estheticinsighits.com',
    app_clinic_name: 'NULL',
    app_address1: 'NULL',
    app_address2: 'NULL',
    app_state: 'NULL',
    app_city: 'NULL',
    app_other_address: 'NULL',
    app_pincode: 'NULL',
    app_date1: '26-03-2020',
    app_date1_time_slot1: '10:00 AM',
    app_date2: 'NULL',
    app_date2_time_slot2: '6:00 PM',
    app_status: 'New',
    app_remarks: 'NULL',
    app_userid: 'NULL',
    confirm_appointment: '1',
    app_confirmation_status: 'Confirmed',
    meeting_status: 'NULL',
    mom: 'NULL',
    assign_to: 'NULL',
    pex_id: 'NULL',
    adedon: '7/6/20',
  },
  {
    app_id: '87',
    app_type: 'NULL',
    app_doc_name: 'Rahul Ranpariya',
    app_doc_mobile: '9979980997',
    app_doc_email: 'rahulranpariya1100@gmail.com',
    app_clinic_name: 'D Y Patil Hospital',
    app_address1: 'Sant Tukaram nagar',
    app_address2: 'Pimpri',
    app_state: 'Maharashtra',
    app_city: 'Pune',
    app_other_address: '',
    app_pincode: '411018',
    app_date1: '10/5/21',
    app_date1_time_slot1: '11:00 AM',
    app_date2: '11/5/21',
    app_date2_time_slot2: '11:00 AM',
    app_status: 'New',
    app_remarks: 'NULL',
    app_userid: '152',
    confirm_appointment: 'NULL',
    app_confirmation_status: 'NULL',
    meeting_status: 'NULL',
    mom: 'NULL',
    assign_to: 'NULL',
    pex_id: 'NULL',
    adedon: '5/3/21',
  },
  {
    app_id: '92',
    app_type: 'NULL',
    app_doc_name: 'Ayesha Chowdhury',
    app_doc_mobile: '7402272418',
    app_doc_email: 'ayeshaschow@gmail.com',
    app_clinic_name: 'Bare Skin Club ',
    app_address1: 'Online',
    app_address2: '',
    app_state: 'Delhi',
    app_city: 'New Delhi',
    app_other_address: '',
    app_pincode: '456001',
    app_date1: '14-03-2022',
    app_date1_time_slot1: '2:00 PM',
    app_date2: '14-03-2022',
    app_date2_time_slot2: '3:00 PM',
    app_status: 'New',
    app_remarks: 'NULL',
    app_userid: '',
    confirm_appointment: 'NULL',
    app_confirmation_status: 'NULL',
    meeting_status: 'NULL',
    mom: 'NULL',
    assign_to: 'NULL',
    pex_id: 'NULL',
    adedon: '3/7/22',
  },
  {
    app_id: '93',
    app_type: 'NULL',
    app_doc_name: 'Ayesha Chowdhury',
    app_doc_mobile: '7402272418',
    app_doc_email: 'ayeshaschow@gmail.com',
    app_clinic_name: 'Bare Skin Club ',
    app_address1: 'Online',
    app_address2: '',
    app_state: 'Delhi',
    app_city: 'New Delhi',
    app_other_address: '',
    app_pincode: '456001',
    app_date1: '14-03-2022',
    app_date1_time_slot1: '2:00 PM',
    app_date2: '14-03-2022',
    app_date2_time_slot2: '3:00 PM',
    app_status: 'New',
    app_remarks: 'NULL',
    app_userid: '',
    confirm_appointment: 'NULL',
    app_confirmation_status: 'NULL',
    meeting_status: 'NULL',
    mom: 'NULL',
    assign_to: 'NULL',
    pex_id: 'NULL',
    adedon: '3/7/22',
  },
  {
    app_id: '94',
    app_type: 'NULL',
    app_doc_name: 'Ayesha Chowdhury',
    app_doc_mobile: '7402272418',
    app_doc_email: 'ayeshaschow@gmail.com',
    app_clinic_name: 'Bare Skin Club ',
    app_address1: 'Online',
    app_address2: '',
    app_state: 'Delhi',
    app_city: 'New Delhi',
    app_other_address: '',
    app_pincode: '456001',
    app_date1: '14-03-2022',
    app_date1_time_slot1: '2:00 PM',
    app_date2: '14-03-2022',
    app_date2_time_slot2: '3:00 PM',
    app_status: 'New',
    app_remarks: 'NULL',
    app_userid: '',
    confirm_appointment: 'NULL',
    app_confirmation_status: 'NULL',
    meeting_status: 'NULL',
    mom: 'NULL',
    assign_to: 'NULL',
    pex_id: 'NULL',
    adedon: '3/7/22',
  },
  {
    app_id: '95',
    app_type: 'NULL',
    app_doc_name: 'Harish ',
    app_doc_mobile: '9738389028',
    app_doc_email: 'harish.harris@gmail.com',
    app_clinic_name: 'Vitals skin klinic ',
    app_address1: '390 ',
    app_address2: '8th main 7th cross BTM 2nd stage ',
    app_state: 'Karnataka',
    app_city: 'Bengaluru',
    app_other_address: '',
    app_pincode: '560076',
    app_date1: '7/4/22',
    app_date1_time_slot1: '11:00 AM',
    app_date2: '7/4/22',
    app_date2_time_slot2: '12:00 PM',
    app_status: 'New',
    app_remarks: 'NULL',
    app_userid: '',
    confirm_appointment: 'NULL',
    app_confirmation_status: 'NULL',
    meeting_status: 'NULL',
    mom: 'NULL',
    assign_to: 'NULL',
    pex_id: 'NULL',
    adedon: '3/31/22',
  },
  {
    app_id: '96',
    app_type: 'NULL',
    app_doc_name: 'Harish ',
    app_doc_mobile: '9738389028',
    app_doc_email: 'harish.harris@gmail.com',
    app_clinic_name: 'Vitals skin klinic ',
    app_address1: '390 ',
    app_address2: '8th main 7th cross BTM 2nd stage ',
    app_state: 'Karnataka',
    app_city: 'Bengaluru',
    app_other_address: '',
    app_pincode: '560076',
    app_date1: '7/4/22',
    app_date1_time_slot1: '11:00 AM',
    app_date2: '7/4/22',
    app_date2_time_slot2: '12:00 PM',
    app_status: 'New',
    app_remarks: 'NULL',
    app_userid: '',
    confirm_appointment: 'NULL',
    app_confirmation_status: 'NULL',
    meeting_status: 'NULL',
    mom: 'NULL',
    assign_to: 'NULL',
    pex_id: 'NULL',
    adedon: '3/31/22',
  },
  {
    app_id: '102',
    app_type: 'NULL',
    app_doc_name: 'Deevi Saikrishna',
    app_doc_mobile: '9848148893',
    app_doc_email: 'saikrishna@estheticinsights.com',
    app_clinic_name: 'krishna',
    app_address1: '41-263, Sanjaypuricolony',
    app_address2: 'JagathgiriGutta',
    app_state: 'Telangana',
    app_city: 'Hyderabad',
    app_other_address: '',
    app_pincode: '500037',
    app_date1: '2/5/23',
    app_date1_time_slot1: '11:00 AM',
    app_date2: '2/5/23',
    app_date2_time_slot2: '2:00 PM',
    app_status: 'completed',
    app_remarks: 'NULL',
    app_userid: '99',
    confirm_appointment: '1',
    app_confirmation_status: 'completed',
    meeting_status: 'NULL',
    mom: 'test',
    assign_to: 'NULL',
    pex_id: 'NULL',
    adedon: '4/25/23',
  },
  {
    app_id: '103',
    app_type: 'NULL',
    app_doc_name: 'Deevi Saikrishna',
    app_doc_mobile: '9848148893',
    app_doc_email: 'saikrishna@estheticinsights.com',
    app_clinic_name: 'krishna',
    app_address1: 'S1 , Kukatpally',
    app_address2: 'Roadno 1',
    app_state: 'Telangana',
    app_city: 'Hyderabad',
    app_other_address: '',
    app_pincode: '500037',
    app_date1: '4/5/23',
    app_date1_time_slot1: '10:00 AM',
    app_date2: '2/5/23',
    app_date2_time_slot2: '4:00 PM',
    app_status: 'New',
    app_remarks: 'NULL',
    app_userid: '99',
    confirm_appointment: '1',
    app_confirmation_status: 'Confirmed',
    meeting_status: 'NULL',
    mom: 'NULL',
    assign_to: 'NULL',
    pex_id: 'NULL',
    adedon: '4/25/23',
  },
  {
    app_id: '104',
    app_type: 'NULL',
    app_doc_name: 'Radhika',
    app_doc_mobile: '9912985875',
    app_doc_email: 'radhikamd@yahoo.com',
    app_clinic_name: 'National skin center ',
    app_address1: 'Plot no 62 , 63 , . Opposite union bank , sikh road ',
    app_address2: 'Diamond Point , Secunderabad ',
    app_state: 'Telangana',
    app_city: 'Hyderabad',
    app_other_address: '',
    app_pincode: '500009',
    app_date1: '8/11/23',
    app_date1_time_slot1: '11:00 AM',
    app_date2: '9/11/23',
    app_date2_time_slot2: '11:00 AM',
    app_status: 'New',
    app_remarks: 'NULL',
    app_userid: '',
    confirm_appointment: 'NULL',
    app_confirmation_status: 'NULL',
    meeting_status: 'NULL',
    mom: 'NULL',
    assign_to: 'NULL',
    pex_id: 'NULL',
    adedon: '10/26/23',
  },
];

