const Joi = require('joi');

const newdevelopmentSchema = Joi.object({
  status: Joi.string().allow('', null),
  customization: Joi.string().allow('', null),
  sale: Joi.string().allow('', null),
  hsn_code: Joi.string().allow('', null),
  product_status: Joi.string().allow('', null),
  product_code: Joi.string().allow('', null),
  generic_name: Joi.string().allow('', null),
  brand_name: Joi.string().allow('', null),
  super_category: Joi.string().allow('', null),
  product_category: Joi.string().allow('', null),
  sub_category: Joi.string().allow('', null),
  sub_sub_category: Joi.string().allow('', null),
  product_sku: Joi.string().allow('', null),
  label_claims: Joi.string().allow('', null),
  product_description_cust: Joi.string().allow('', null),
  product_description: Joi.string().allow('', null),
  product_price: Joi.number().allow(null),
  tax_rate: Joi.number().allow(null),
  gst_input: Joi.string().allow('', null),
  product_cover_image: Joi.string().allow('', null),
  product_cover_image_customization: Joi.string().allow('', null),
  product_ingrediants: Joi.string().allow('', null),
  excepients: Joi.string().allow('', null),
  indications: Joi.string().allow('', null),
  usage: Joi.string().allow('', null),
  cautions: Joi.string().allow('', null),
  application_area: Joi.string().allow('', null),
  dosage_form_type: Joi.string().allow('', null),
  phrange: Joi.string().allow('', null),
  color: Joi.string().allow('', null),
  fragrance: Joi.string().allow('', null),
  vascosity: Joi.string().allow('', null),
  other_specs: Joi.string().allow('', null),
  technology_used: Joi.string().allow('', null),
  recomendedproducts: Joi.string().allow('', null),
  packing_recommendations: Joi.string().allow('', null),
  batch_no: Joi.string().allow('', null),
  sub_cat_char: Joi.string().allow('', null),
  grid_sub_cat: Joi.string().allow('', null),
  skin_type: Joi.string().allow('', null),
  product_specializations: Joi.string().allow('', null),
  usage_time: Joi.string().allow('', null),
  application_specifications: Joi.string().allow('', null)
});

module.exports = {
  newdevelopmentSchema
};
